/** Check-in confirmation copy — tr / en / pt-BR */

const SLUGS = [
  "custom",
  "mental-clarity",
  "moving-body",
  "lifelong-learner",
  "self-care",
  "creator",
  "deep-focus",
  "night-owl",
  "social-builder",
];

const CONTENT = {
  tr: {
    subtitle: "Doğru cevap yok — dürüst bir işaret yeter. Detayları sonra düşünürsün.",
    otherPlaceholder: "Kendi cümlenle kısaca yaz…",
    save: "Kaydet ve Tamamla",
    slugs: {
      custom: {
        title: "Bugün bu kimlik yönünde neredeydin?",
        subtitle: "Küçük adım, yarım kalan veya sadece fark etmek — hepsi sayılır.",
        options: [
          "İstediğim gibi ilerledim",
          "Kısmen yaptım, yarıda kaldı",
          "Zorlandım ama yine de denedim",
          "Enerjim düşüktü, mini sürüm yaptım",
          "Başka öncelikler öne geçti",
          "Sadece niyet ettim, hareket az",
          "Bugün dinlenmeyi seçtim",
          "Hızlı bir not almak yeterli oldu",
        ],
      },
      "mental-clarity": {
        title: "Zihni berrak biri olarak bugün neredeydin?",
        subtitle: "Dağınıklık da veri — yazmak veya fark etmek bile ilerlemedir.",
        options: [
          "Kaygıyı veya düşünceyi not ettim",
          "Zihnimi tek önceliğe indirdim",
          "Kısa nefes + tek cümle yeterli oldu",
          "Kararsızlığı azalttım, netleştim",
          "Sadece fark ettim, yazmadım",
          "Dağınık geçti — yine de gözlemledim",
          "Bugün zihin dinlenmesi gerekti",
          "Yarın için tek satır plan bıraktım",
        ],
      },
      "moving-body": {
        title: "Hareket eden biri olarak bugün neredeydin?",
        subtitle: "30 saniye bile sayılır — mükemmellik değil, görünürlük.",
        options: [
          "Planladığım hareketi tamamladım",
          "Kısa hareket / esneme yeterli oldu",
          "Yürüyüş veya merdiven bile ivme verdi",
          "Vücudumu dinledim, dinlendim",
          "Zaman yetmedi ama niyet vardı",
          "Yarım kaldı — yine de denedim",
          "Ağrı/yorgunluk vardı, mini sürüm",
          "Bugün hareket şart değildi",
        ],
      },
      "lifelong-learner": {
        title: "Öğrenen biri olarak bugün neredeydin?",
        subtitle: "Bir satır, bir sayfa, bir merak — hepsi öğrenme sinyali.",
        options: [
          "Küçük bir şey okudum veya izledim",
          "Not aldım veya tekrar ettim",
          "Kaynağı açıp tek adım attım",
          "Sadece merak ettim, kaydettim",
          "Bugün olmadı — sorun değil",
          "Yarın telafi için işaret bıraktım",
          "Öğrenmeyi iş/günlük hayata bağladım",
          "Kısa da olsa yeni bir fikir yakaladım",
        ],
      },
      "self-care": {
        title: "Kendine iyi bakan biri olarak bugün neredeydin?",
        subtitle: "İyilik küçük olabilir — sınır, mola, su, nefes.",
        options: [
          "Kendime küçük bir iyilik yaptım",
          "Dinlenmeye bilinçli izin verdim",
          "Sınır koydum veya hayır dedim",
          "Kısa mola + nefes aldım",
          "Farkındalık anı yakaladım",
          "Bugün zordu, yine de fark ettim",
          "Su / uyku / beslenmeye dikkat ettim",
          "Kendime yargısız davrandım",
        ],
      },
      creator: {
        title: "Üreten biri olarak bugün neredeydin?",
        subtitle: "Taslak, tek kelime, tek satır — üretim böyle başlar.",
        options: [
          "Üzerinde çalıştım, ilerleme oldu",
          "Taslak veya fikir çıkardım",
          "Az da olsa somut bir adım",
          "Sadece başlamak yetti",
          "Beklentimi düşürdüm, devam ettim",
          "Bugün üretim günü değildi",
          "Düzenleme yerine ham çıktı verdim",
          "Yarın için tek cümlelik plan yazdım",
        ],
      },
      "deep-focus": {
        title: "Odaklı çalışan biri olarak bugün neredeydin?",
        subtitle: "Derin blok, tek görev veya 5 dk odak — hepsi geçerli.",
        options: [
          "Tek göreve kilitlendim, iyi hissettim",
          "Kısa odak bloğu bile fark yarattı",
          "Dikkat dağıtıcıları bir süre kestim",
          "Başlamak zordu ama birkaç dk odaklandım",
          "Tek sekme / tek iş kuralını denedim",
          "Dağınık geçti — yine de fark ettim",
          "Bugün odak şart değildi, dinlendim",
          "Yarın için net odak planı kurdum",
        ],
      },
      "night-owl": {
        title: "Akşam ritmini koruyan biri olarak bugün neredeydin?",
        subtitle: "Gece sürümü her zaman küçük — uyku önceliğini koru.",
        options: [
          "Planladığım akşam adımını yaptım",
          "Enerji düşük ama mini adım attım",
          "Ekranı erken bırakmayı denedim",
          "Nefes veya sakin kapanış yaptım",
          "Gün yoğundu, yarına bıraktım",
          "Erken pes ettim — yargı yok",
          "Tek küçük şey bile ritmi korudu",
          "Bugün gece rutini atlandı",
        ],
      },
      "social-builder": {
        title: "Bağ kuran biri olarak bugün neredeydin?",
        subtitle: "Mesaj, dinleme veya minik etkileşim — bağlantı küçük başlar.",
        options: [
          "Birine ulaştım veya yazdım",
          "Minik bir etkileşim / selam",
          "Dinledim veya destek oldum",
          "Kendime zaman ayırdım — bu da bağ",
          "Bugün yalnız hissettim, fark ettim",
          "Atladım — yarın için niyet bıraktım",
          "Taslak mesaj yazdım, göndermedim bile",
          "Yüz yüze kısa bir temas oldu",
        ],
      },
    },
  },
  en: {
    subtitle: "No wrong answer — an honest mark is enough. Details can wait.",
    otherPlaceholder: "Write briefly in your own words…",
    save: "Save and complete",
    slugs: {
      custom: {
        title: "Where were you today on this identity path?",
        subtitle: "Small step, half-done, or just noticing — all count.",
        options: [
          "I progressed as I wanted",
          "I did it partly, left it unfinished",
          "I struggled but still tried",
          "Energy was low — I did a mini version",
          "Other priorities came first",
          "I only intended, little action",
          "Today I chose rest",
          "A quick note was enough",
        ],
      },
      "mental-clarity": {
        title: "As someone who values mental clarity, where were you today?",
        subtitle: "Scattered is data too — writing or noticing still moves you forward.",
        options: [
          "I noted the worry or thought",
          "I narrowed my mind to one priority",
          "Short breath + one sentence was enough",
          "I reduced indecision, got clearer",
          "I only noticed, didn't write",
          "Scattered day — I still observed",
          "Today my mind needed rest",
          "I left a one-line plan for tomorrow",
        ],
      },
      "moving-body": {
        title: "As someone who moves their body, where were you today?",
        subtitle: "Even 30 seconds counts — visibility, not perfection.",
        options: [
          "I completed the movement I planned",
          "Short move / stretch was enough",
          "Walk or stairs still gave momentum",
          "I listened to my body and rested",
          "No time, but intention was there",
          "Half-done — I still tried",
          "Sore/tired — mini version only",
          "Movement wasn't needed today",
        ],
      },
      "lifelong-learner": {
        title: "As a lifelong learner, where were you today?",
        subtitle: "One line, one page, one curiosity — all learning signals.",
        options: [
          "I read or watched something small",
          "I took notes or reviewed",
          "I opened the source and took one step",
          "I only got curious and logged it",
          "Didn't happen today — that's okay",
          "Left a marker to catch up tomorrow",
          "I linked learning to daily life",
          "Caught a new idea, even briefly",
        ],
      },
      "self-care": {
        title: "As someone who practices self-care, where were you today?",
        subtitle: "Kindness can be small — boundary, break, water, breath.",
        options: [
          "I did a small kindness for myself",
          "I consciously allowed rest",
          "I set a boundary or said no",
          "Short break + breath",
          "I caught a moment of awareness",
          "Hard day — I still noticed",
          "I paid attention to water/sleep/food",
          "I treated myself without judgment",
        ],
      },
      creator: {
        title: "As a creator, where were you today?",
        subtitle: "Draft, one word, one line — creation starts there.",
        options: [
          "I worked on it — progress happened",
          "A draft or idea came out",
          "A small concrete step",
          "Starting was enough",
          "I lowered expectations and continued",
          "Today wasn't a production day",
          "Raw output over editing",
          "I wrote a one-line plan for tomorrow",
        ],
      },
      "deep-focus": {
        title: "As a focused worker, where were you today?",
        subtitle: "Deep block, single task, or 5 min focus — all valid.",
        options: [
          "I locked onto one task — felt good",
          "Even a short focus block helped",
          "I cut distractions for a while",
          "Hard to start but focused a few minutes",
          "I tried one tab / one task rule",
          "Scattered day — I still noticed",
          "Focus wasn't needed today — I rested",
          "I set a clear focus plan for tomorrow",
        ],
      },
      "night-owl": {
        title: "As someone who protects evening rhythm, where were you today?",
        subtitle: "Night version is always smaller — protect your sleep.",
        options: [
          "I did my planned evening step",
          "Low energy but a mini step",
          "I tried to leave the screen earlier",
          "Breath or calm wind-down",
          "Busy day — moved to tomorrow",
          "Gave up early — no judgment",
          "One small thing kept the rhythm",
          "Evening routine skipped today",
        ],
      },
      "social-builder": {
        title: "As someone who builds connection, where were you today?",
        subtitle: "Message, listening, or tiny interaction — connection starts small.",
        options: [
          "I reached out or wrote to someone",
          "A tiny interaction / hello",
          "I listened or supported someone",
          "I took time for myself — that counts too",
          "Felt lonely today — I noticed",
          "Skipped — left intention for tomorrow",
          "Drafted a message, didn't even send",
          "Brief in-person contact happened",
        ],
      },
    },
  },
  "pt-BR": {
    subtitle: "Não há resposta errada — um registro honesto basta. Detalhes depois.",
    otherPlaceholder: "Escreva brevemente com suas palavras…",
    save: "Salvar e concluir",
    slugs: {
      custom: {
        title: "Onde você esteve hoje nesse caminho de identidade?",
        subtitle: "Passo pequeno, pela metade ou só perceber — tudo conta.",
        options: [
          "Avancei como queria",
          "Fiz em parte, ficou incompleto",
          "Foi difícil mas tentei",
          "Energia baixa — fiz versão mínima",
          "Outras prioridades vieram primeiro",
          "Só tive intenção, pouca ação",
          "Hoje escolhi descansar",
          "Uma nota rápida bastou",
        ],
      },
      "mental-clarity": {
        title: "Como alguém que busca clareza mental, onde esteve hoje?",
        subtitle: "Dispersão também é dado — escrever ou perceber já é avanço.",
        options: [
          "Anotei a preocupação ou pensamento",
          "Reduzi a mente a uma prioridade",
          "Respiração curta + uma frase bastou",
          "Reduzi indecisão, ficou mais claro",
          "Só percebi, não escrevi",
          "Dia disperso — ainda observei",
          "Hoje a mente precisava de descanso",
          "Deixei plano de uma linha para amanhã",
        ],
      },
      "moving-body": {
        title: "Como alguém que move o corpo, onde esteve hoje?",
        subtitle: "30 segundos contam — visibilidade, não perfeição.",
        options: [
          "Completei o movimento planejado",
          "Movimento curto / alongamento bastou",
          "Caminhada ou escadas deram impulso",
          "Ouvi o corpo e descansei",
          "Sem tempo, mas houve intenção",
          "Ficou pela metade — ainda tentei",
          "Dor/cansaço — só versão mínima",
          "Movimento não era necessário hoje",
        ],
      },
      "lifelong-learner": {
        title: "Como aprendiz contínuo, onde esteve hoje?",
        subtitle: "Uma linha, uma página, uma curiosidade — sinal de aprendizado.",
        options: [
          "Li ou vi algo pequeno",
          "Fiz anotações ou revisei",
          "Abri a fonte e dei um passo",
          "Só fiquei curioso e registrei",
          "Não rolou hoje — tudo bem",
          "Deixei marca para amanhã",
          "Liguei aprendizado ao dia a dia",
          "Capturei ideia nova, mesmo breve",
        ],
      },
      "self-care": {
        title: "Como alguém que pratica autocuidado, onde esteve hoje?",
        subtitle: "Gentileza pode ser pequena — limite, pausa, água, respiração.",
        options: [
          "Fiz um pequeno favor a mim",
          "Permiti descanso conscientemente",
          "Coloquei limite ou disse não",
          "Pausa curta + respiração",
          "Capturei momento de consciência",
          "Dia difícil — ainda percebi",
          "Cuidei de água/sono/alimentação",
          "Tratei-me sem julgamento",
        ],
      },
      creator: {
        title: "Como criador, onde esteve hoje?",
        subtitle: "Rascunho, uma palavra, uma linha — criação começa assim.",
        options: [
          "Trabalhei nisso — houve progresso",
          "Saiu rascunho ou ideia",
          "Um passo concreto pequeno",
          "Começar bastou",
          "Baixei expectativa e continuei",
          "Hoje não era dia de produção",
          "Saída bruta em vez de editar",
          "Escrevi plano de uma linha para amanhã",
        ],
      },
      "deep-focus": {
        title: "Como trabalhador focado, onde esteve hoje?",
        subtitle: "Bloco profundo, tarefa única ou 5 min de foco — tudo vale.",
        options: [
          "Travei em uma tarefa — senti bem",
          "Até bloco curto de foco ajudou",
          "Cortei distrações por um tempo",
          "Difícil começar mas foquei alguns min",
          "Tentei regra de uma aba / uma tarefa",
          "Dia disperso — ainda percebi",
          "Foco não era necessário — descansei",
          "Montei plano claro de foco para amanhã",
        ],
      },
      "night-owl": {
        title: "Como quem protege o ritmo noturno, onde esteve hoje?",
        subtitle: "Versão noturna é sempre menor — proteja o sono.",
        options: [
          "Fiz o passo noturno planejado",
          "Energia baixa mas passo mínimo",
          "Tentei largar a tela mais cedo",
          "Respiração ou desaceleração calma",
          "Dia cheio — deixei para amanhã",
          "Desisti cedo — sem julgamento",
          "Uma coisa pequena manteve o ritmo",
          "Rotina noturna pulada hoje",
        ],
      },
      "social-builder": {
        title: "Como quem constrói conexão, onde esteve hoje?",
        subtitle: "Mensagem, escuta ou interação mínima — conexão começa pequena.",
        options: [
          "Falei ou escrevi para alguém",
          "Interação mínima / oi",
          "Escutei ou apoiei alguém",
          "Tempo para mim — isso também conta",
          "Me senti sozinho — percebi",
          "Pulei — deixei intenção para amanhã",
          "Rascunhei mensagem, nem enviei",
          "Contato breve presencial aconteceu",
        ],
      },
    },
  },
};

module.exports = { CONTENT, SLUGS };
