/**
 * Merges journeyMoments + refreshed coachNotes + improved dailyPrinciples (days 1–14) into tr/en/pt-BR.
 */
const fs = require("fs");
const path = require("path");

const localesDir = path.join(__dirname, "..", "src", "i18n", "locales");

const journeyMoments = {
  tr: {
    byDay: {
      "1": "İlk gün: mükemmellik değil, başlangıç sayılır. Beyin bugün kayıt defterini açıyor — çıtayı yere indirmek en akıllı hamle.",
      "2": "İkinci tekrar: duygu gelip geçer; bugün attığın küçük adım kalır.",
      "3": "Üçüncü gün: bağlantılar henüz ince — her tekrar sinirlere bir ip daha atıyor.",
      "4": "Dördüncü gün: net bir 'eğer-şu olursa' planı, rastgele motivasyondan güçlüdür.",
      "5": "Beşinci gün: iradeyi zorlamak yerine ortamı düzenlemek kazandırır.",
      "6": "Altıncı gün: kimlik önce bir cümle, sonra tutarlı hareketle büyür.",
      "8": "İkinci haftanın eşiği: ritim aranıyor, acele yok — görünür olmak yeterli.",
      "9": "Dokuzuncu gün: küçük tamamlama hissi, beynin 'devam et' sinyalidir.",
      "10": "Onuncu gün: yoğunluk değil, tekrar eden varlık hedefin.",
      "11": "On birinci gün: zihin dağılsa bile tek tekrar günü kurtarır.",
      "12": "On ikinci gün: aynı çapa, aynı saat — beyin deseni tanımaya başlar.",
      "13": "On üçüncü gün: iki haftaya bir adım kala sabır, hızdan değerlidir.",
      "15": "On beşinci gün: alışkanlık artık 'deneme' değil, günlük bir iz.",
      "16": "On altıncı gün: eski yol hâlâ cazip — yeni yol her geçişte güçlenir.",
      "17": "On yedinci gün: kendine şefkat, mazeret değil; yarın için yakıt.",
      "18": "On sekizinci gün: planlı tetik, düşünmeden başlamanın anahtarı.",
      "19": "On dokuzuncu gün: sıkıcı hissetmek normal — otomasyon yavaş inşa edilir.",
      "20": "Yirminci gün: üç hafta yaklaşıyor; küçük adımlar büyük fark yaratır.",
      "21": "Yirmi birinci gün: Faz 1'in son virajı — tutarlılık kimliğe dönüşüyor.",
      "23": "Faz 2 kapısı: tutarlılık baskınleşince kimlik tonu daha net duyulur.",
      "24": "Yirmi dördüncü gün: artık 'yapmalı mıyım?' değil, 'nasıl yaparım?' sorusu.",
      "25": "Yirmi beşinci gün: ölçüm, yargı değil — veri seni ileri taşır.",
      "26": "Yirmi altıncı gün: direnç kas gibi; kısa nefes + tek tekrar yeter.",
      "27": "Yirmi yedinci gün: takdiri geçmişe değil, bugünkü çabaya ver.",
      "28": "Yirmi sekizinci gün: farklı bağlamda aynı adım, genellemenin anahtarı.",
      "29": "Yirmi dokuzuncu gün: ödül abartı değil, tamamlandı sinyali olsun.",
      "31": "Otuz birinci gün: stres fırsat da olabilir — sürümü küçült, devam et.",
      "32": "Otuz ikinci gün: kaçırma öğrenme penceresi; yarın için 30 sn plan yeter.",
      "33": "Otuz üçüncü gün: erteleme 'şimdi acı vermez' der — plan onu kırar.",
      "34": "Otuz dördüncü gün: bir cümlelik hesap verebilirlik, hatırlatmanın ötesine geçer.",
      "35": "Otuz beşinci gün: tükenme sinyali = hedefi küçült, dinlenmeyi erteleme.",
      "36": "Otuz altıncı gün: iç sesin tonu, davranışı şekillendirir.",
      "37": "Otuz yedinci gün: bitişe yaklaşırken tempo artabilir — ritmi koru.",
      "38": "Otuz sekizinci gün: tutarsızlık hissi, beynin uyum arayışıdır.",
      "39": "Otuz dokuzuncu gün: yarım saniye bile sayılır — zinciri koparma.",
      "40": "Kırkıncı gün: Faz 2'nin sonları — otomasyon hissedilmeye başlar.",
      "41": "Kırk birinci gün: yeni ipuçları, eski davranışı yeniden yazar.",
      "42": "Kırk ikinci gün: içsel pekiştirme, uzun vadeli motivasyonun kaynağı.",
      "43": "Kırk üçüncü gün: niyet ile eylem arasındaki boşluk kayıtla kapanır.",
      "45": "Faz 3: çoğu hareket hâlâ fark edilmez; yol artık senden geliyor gibi.",
      "46": "Kırk altıncı gün: otomasyon farkındalığı azaltır — enerjini başka yere bırak.",
      "47": "Kırk yedinci gün: bazal devreler devreye giriyor; ön lob yükü hafifliyor.",
      "48": "Kırk sekizinci gün: zihinsel yük azalınca hedefler yükselir.",
      "49": "Kırk dokuzuncu gün: herkesin hızı farklı — kendi eğrinde kal.",
      "50": "Elliinci gün: rutin, dopamin dalgası değil; tekrarın sürekliliği.",
      "51": "Elli birinci gün: kimlik cümlesi ve davranış birbirini besliyor.",
      "52": "Elli ikinci gün: bağlam değişince alışkanlık test edilir — plan hazır olsun.",
      "53": "Elli üçüncü gün: kayma riski yüksek; if-then planı cebinde tut.",
      "54": "Elli dördüncü gün: tetikleri adlandırmak, toparlanmayı hızlandırır.",
      "55": "Elli beşinci gün: erteleme gelecek ödülü küçültür — bugünkü sürümü seç.",
      "56": "Elli altıncı gün: hedefe yaklaşırken hızlanma normal; tükenmeye dikkat.",
      "57": "Elli yedinci gün: fazla planlama yerine basit yürütme.",
      "58": "Elli sekizinci gün: son viraj — if-then ile riski kapat.",
      "59": "Elli dokuzuncu gün: aynı çekirdek, genişleyen sınır — sürdürülebilir büyüme.",
      "60": "Altmışıncı gün: ritim artık senin; küçük sapmalar panik değil, veri.",
      "61": "Altmış birinci gün: örtük öğrenme derinleşiyor — tekrar kaliteyi taşır.",
      "62": "Altmış ikinci gün: bağlam değişimi fırsat; ölçülü yenileme yeter.",
      "63": "Altmış üçüncü gün: sistem 1 güçlenirken sistem 2 ortamı ayarlar.",
      "64": "Altmış dördüncü gün: kayıt tutmak, kör noktaları görünür kılar.",
      "65": "Altmış beşinci gün: son günler — ritmi koru, yeni dev hedef ekleme.",
    },
    pool: [
      "Bugün küçük bir adım, yarınki seni güçlü tutar.",
      "Mükemmel gün şart değil — görünür gün yeterli.",
      "Duygu dalgalanır; sistem ve çapa kalır.",
      "Tek tekrar, zinciri koparmamak için bazen yeterlidir.",
      "Beyin bugün de kayıt tutuyor — küçük de olsa işaretle.",
      "Yavaş ilerlemek, durmaktan her zaman iyidir.",
      "Kendine şefkat, disiplinin karşıtı değil; yakıtıdır.",
      "Planlı başlangıç, rastgele motivasyondan daha güvenilir.",
      "Ortamı biraz düzenlemek, iradeyi yormadan kazandırır.",
      "Bugün 'nasıl hissediyorum?' değil, 'ne kadar küçük yapabilirim?' sorusu.",
      "Tutarlılık, yoğunluktan daha değerlidir.",
      "Eski alışkanlık hâlâ cazip olabilir — bu normal, yeni yol güçleniyor.",
      "Bir derin nefes + tek tekrar, günü kurtarabilir.",
      "Kimlik, büyük sözlerle değil; tekrar eden küçük hareketlerle inşa edilir.",
      "Kaçırma bir son değil; yarın için veri toplama anı.",
      "Stresli günlerde sürümü küçült — varlık önemli, mükemmellik değil.",
      "Çapa aynı kalsın; beyin deseni tanımak için süreklilik ister.",
      "Bugünkü sen, dünkü senden bir adım daha güçlü olabilir.",
      "Otomasyon sabırsızlık gerektirir — sıkıcılık ilerlemenin parçası.",
      "Kendini ölç, yargılama; veri ilerlemenin haritasıdır.",
      "Hedefe yaklaşırken tempo artabilir — nefesini ve ritmini koru.",
      "Tek cümlelik niyet, günün geri kalanını hafifletir.",
      "Bu yolculuk 66 gün değil; her gün yeniden seçilen bir alışkanlık.",
      "Bugün burada olman, zaten önemli bir kazanım.",
    ],
  },
  en: {
    byDay: {
      "1": "Day one: starting counts, not perfection. Your brain opens the logbook today — lowering the bar is the smart move.",
      "2": "Second rep: feelings pass; the small step you take today stays.",
      "3": "Day three: connections are still thin — each repeat throws another thread.",
      "4": "Day four: a clear if-then plan beats random motivation.",
      "5": "Day five: shaping the environment wins more than forcing willpower.",
      "6": "Day six: identity starts as a sentence, then grows through consistent action.",
      "8": "Second week threshold: rhythm is forming — being visible is enough.",
      "9": "Day nine: a small sense of completion is the brain's 'keep going' signal.",
      "10": "Day ten: repeated presence beats intensity.",
      "11": "Day eleven: even one rep saves the day when the mind wanders.",
      "12": "Day twelve: same anchor, same time — the brain starts recognizing the pattern.",
      "13": "Day thirteen: one step from two weeks — patience beats speed.",
      "15": "Day fifteen: the habit is no longer a trial — it's a daily trace.",
      "16": "Day sixteen: the old path still tempts — the new one strengthens each pass.",
      "17": "Day seventeen: self-compassion is fuel, not an excuse.",
      "18": "Day eighteen: a planned trigger is the key to starting without overthinking.",
      "19": "Day nineteen: boredom is normal — automation builds slowly.",
      "20": "Day twenty: three weeks near — small steps compound.",
      "21": "Day twenty-one: last bend of Phase 1 — consistency is turning into identity.",
      "23": "Phase 2 threshold: as consistency dominates, your identity tone sounds clearer.",
      "24": "Day twenty-four: the question shifts from 'should I?' to 'how do I?'",
      "25": "Day twenty-five: measurement is data, not judgment.",
      "26": "Day twenty-six: resistance is like a muscle — one breath + one rep is enough.",
      "27": "Day twenty-seven: credit today's effort, not yesterday's story.",
      "28": "Day twenty-eight: same step in a new context unlocks generalization.",
      "29": "Day twenty-nine: reward is a completion signal, not exaggeration.",
      "31": "Day thirty-one: stress can be a cue — shrink the version, keep going.",
      "32": "Day thirty-two: a miss is a learning window — a 30-sec plan for tomorrow is enough.",
      "33": "Day thirty-three: procrastination says 'no pain now' — your plan breaks that.",
      "34": "Day thirty-four: one sentence of accountability goes beyond reminders.",
      "35": "Day thirty-five: exhaustion signal = shrink the target, don't skip rest.",
      "36": "Day thirty-six: the tone of your inner voice shapes behavior.",
      "37": "Day thirty-seven: pace may rise near the end — protect your rhythm.",
      "38": "Day thirty-eight: inconsistency feeling is the brain seeking alignment.",
      "39": "Day thirty-nine: even half a second counts — don't break the chain.",
      "40": "Day forty: late Phase 2 — automation starts to be felt.",
      "41": "Day forty-one: new cues rewrite the old behavior.",
      "42": "Day forty-two: internal reinforcement fuels long-term motivation.",
      "43": "Day forty-three: recording closes the gap between intention and action.",
      "45": "Phase 3: most moves still go unnoticed — the path now feels like it comes from you.",
      "46": "Day forty-six: automation frees awareness — spend energy elsewhere.",
      "47": "Day forty-seven: basal circuits engage; prefrontal load lightens.",
      "48": "Day forty-eight: as mental load drops, higher goals emerge.",
      "49": "Day forty-nine: everyone's pace differs — stay on your curve.",
      "50": "Day fifty: routine is continuity of repetition, not a dopamine wave.",
      "51": "Day fifty-one: identity sentence and behavior feed each other.",
      "52": "Day fifty-two: context change tests the habit — keep a plan ready.",
      "53": "Day fifty-three: slip risk is high — keep your if-then in pocket.",
      "54": "Day fifty-four: naming triggers speeds recovery.",
      "55": "Day fifty-five: delay shrinks future reward — choose today's version.",
      "56": "Day fifty-six: acceleration near the goal is normal — watch for burnout.",
      "57": "Day fifty-seven: simple execution beats over-planning.",
      "58": "Day fifty-eight: final stretch — close risk with if-then.",
      "59": "Day fifty-nine: same core, expanding edge — sustainable growth.",
      "60": "Day sixty: rhythm is yours; small slips are data, not panic.",
      "61": "Day sixty-one: implicit learning deepens — repetition carries quality.",
      "62": "Day sixty-two: context shift is opportunity; measured renewal is enough.",
      "63": "Day sixty-three: as System 1 strengthens, System 2 shapes the environment.",
      "64": "Day sixty-four: tracking makes blind spots visible.",
      "65": "Day sixty-five: final days — keep rhythm, don't add a huge new goal.",
    },
    pool: [
      "A small step today keeps tomorrow-you stronger.",
      "You don't need a perfect day — a visible day is enough.",
      "Feelings fluctuate; your system and anchor remain.",
      "One rep is sometimes enough to keep the chain alive.",
      "Your brain is logging today too — mark it, even small.",
      "Slow progress always beats standing still.",
      "Self-compassion isn't the opposite of discipline — it's fuel.",
      "A planned start beats random motivation.",
      "Tweaking the environment wins without draining willpower.",
      "Today ask 'how small can I go?' not 'how do I feel?'",
      "Consistency matters more than intensity.",
      "The old habit may still tempt you — that's normal; the new path is strengthening.",
      "One deep breath + one rep can save the day.",
      "Identity is built by small repeated moves, not big speeches.",
      "A miss isn't the end — it's data for tomorrow.",
      "On stressful days, shrink the version — presence over perfection.",
      "Keep the anchor steady; the brain needs continuity to learn the pattern.",
      "Today's you can be one step stronger than yesterday's.",
      "Automation requires patience — boredom is part of progress.",
      "Measure yourself, don't judge; data is your map.",
      "Pace may rise as you approach the goal — protect your breath and rhythm.",
      "One sentence of intention lightens the rest of the day.",
      "This journey isn't 66 days — it's a habit re-chosen every day.",
      "Showing up today is already a meaningful win.",
    ],
  },
  "pt-BR": {
    byDay: {
      "1": "Dia um: começar conta, não a perfeição. O cérebro abre o caderno hoje — baixar a barra é o movimento inteligente.",
      "2": "Segunda repetição: sentimentos passam; o pequeno passo de hoje fica.",
      "3": "Dia três: conexões ainda finas — cada repetição lança mais um fio.",
      "4": "Dia quatro: um plano se-então claro vence motivação aleatória.",
      "5": "Dia cinco: moldar o ambiente ganha mais que forçar força de vontade.",
      "6": "Dia seis: identidade começa como frase, depois cresce com ação consistente.",
      "8": "Limite da segunda semana: o ritmo se forma — ser visível basta.",
      "9": "Dia nove: uma pequena sensação de conclusão é o sinal de 'continuar'.",
      "10": "Dia dez: presença repetida vence intensidade.",
      "11": "Dia onze: uma repetição salva o dia quando a mente dispersa.",
      "12": "Dia doze: mesma âncora, mesmo horário — o cérebro reconhece o padrão.",
      "13": "Dia treze: um passo das duas semanas — paciência vence velocidade.",
      "15": "Dia quinze: o hábito não é mais teste — é um rastro diário.",
      "16": "Dia dezesseis: o caminho antigo ainda tenta — o novo fortalece a cada passagem.",
      "17": "Dia dezessete: autocompaixão é combustível, não desculpa.",
      "18": "Dia dezoito: gatilho planejado é a chave para começar sem pensar demais.",
      "19": "Dia dezenove: tédio é normal — automação se constrói devagar.",
      "20": "Dia vinte: três semanas perto — passos pequenos se acumulam.",
      "21": "Dia vinte e um: última curva da Fase 1 — consistência vira identidade.",
      "23": "Limite da Fase 2: com consistência dominante, o tom da identidade soa mais claro.",
      "24": "Dia vinte e quatro: a pergunta muda de 'devo?' para 'como faço?'",
      "25": "Dia vinte e cinco: medição é dado, não julgamento.",
      "26": "Dia vinte e seis: resistência é como músculo — uma respiração + uma rep basta.",
      "27": "Dia vinte e sete: credite o esforço de hoje, não a história de ontem.",
      "28": "Dia vinte e oito: mesmo passo em novo contexto desbloqueia generalização.",
      "29": "Dia vinte e nove: recompensa é sinal de conclusão, não exagero.",
      "31": "Dia trinta e um: estresse pode ser pista — encolha a versão, siga.",
      "32": "Dia trinta e dois: uma falha é janela de aprendizado — plano de 30s para amanhã basta.",
      "33": "Dia trinta e três: procrastinação diz 'sem dor agora' — seu plano quebra isso.",
      "34": "Dia trinta e quatro: uma frase de responsabilidade vai além de lembretes.",
      "35": "Dia trinta e cinco: sinal de exaustão = encolher meta, não pular descanso.",
      "36": "Dia trinta e seis: o tom da voz interna molda o comportamento.",
      "37": "Dia trinta e sete: o ritmo pode subir perto do fim — proteja seu compasso.",
      "38": "Dia trinta e oito: sensação de inconsistência é o cérebro buscando alinhamento.",
      "39": "Dia trinta e nove: meio segundo conta — não quebre a corrente.",
      "40": "Dia quarenta: fim da Fase 2 — automação começa a ser sentida.",
      "41": "Dia quarenta e um: novas pistas reescrevem o comportamento antigo.",
      "42": "Dia quarenta e dois: reforço interno alimenta motivação de longo prazo.",
      "43": "Dia quarenta e três: registrar fecha a lacuna entre intenção e ação.",
      "45": "Fase 3: a maioria dos movimentos ainda passa despercebida — o caminho parece vir de você.",
      "46": "Dia quarenta e seis: automação libera consciência — gaste energia em outro lugar.",
      "47": "Dia quarenta e sete: circuitos basais entram; carga pré-frontal alivia.",
      "48": "Dia quarenta e oito: com carga mental menor, metas maiores emergem.",
      "49": "Dia quarenta e nove: cada um tem seu ritmo — fique na sua curva.",
      "50": "Dia cinquenta: rotina é continuidade de repetição, não onda de dopamina.",
      "51": "Dia cinquenta e um: frase de identidade e comportamento se alimentam.",
      "52": "Dia cinquenta e dois: mudança de contexto testa o hábito — tenha plano pronto.",
      "53": "Dia cinquenta e três: risco de escorregão alto — mantenha se-então no bolso.",
      "54": "Dia cinquenta e quatro: nomear gatilhos acelera recuperação.",
      "55": "Dia cinquenta e cinco: adiar encolhe recompensa futura — escolha a versão de hoje.",
      "56": "Dia cinquenta e seis: aceleração perto da meta é normal — cuidado com esgotamento.",
      "57": "Dia cinquenta e sete: execução simples vence planejamento excessivo.",
      "58": "Dia cinquenta e oito: reta final — feche risco com se-então.",
      "59": "Dia cinquenta e nove: mesmo núcleo, borda expandindo — crescimento sustentável.",
      "60": "Dia sessenta: ritmo é seu; pequenos deslizes são dados, não pânico.",
      "61": "Dia sessenta e um: aprendizado implícito aprofunda — repetição carrega qualidade.",
      "62": "Dia sessenta e dois: mudança de contexto é oportunidade; renovação medida basta.",
      "63": "Dia sessenta e três: Sistema 1 fortalece, Sistema 2 molda o ambiente.",
      "64": "Dia sessenta e quatro: registro torna pontos cegos visíveis.",
      "65": "Dia sessenta e cinco: dias finais — mantenha ritmo, não adicione meta gigante.",
    },
    pool: [
      "Um passo pequeno hoje fortalece o você de amanhã.",
      "Não precisa de dia perfeito — um dia visível basta.",
      "Sentimentos oscilam; sistema e âncora permanecem.",
      "Uma repetição às vezes basta para manter a corrente.",
      "O cérebro também registra hoje — marque, mesmo pequeno.",
      "Progresso lento sempre vence ficar parado.",
      "Autocompaixão não é oposto de disciplina — é combustível.",
      "Começo planejado vence motivação aleatória.",
      "Ajustar o ambiente ganha sem esgotar força de vontade.",
      "Hoje pergunte 'quão pequeno posso ir?' não 'como me sinto?'",
      "Consistência importa mais que intensidade.",
      "O hábito antigo ainda pode tentar — é normal; o novo caminho fortalece.",
      "Uma respiração profunda + uma rep pode salvar o dia.",
      "Identidade se constrói com movimentos pequenos repetidos, não discursos.",
      "Uma falha não é o fim — é dado para amanhã.",
      "Em dias estressantes, encolha a versão — presença sobre perfeição.",
      "Mantenha a âncora firme; o cérebro precisa de continuidade.",
      "O você de hoje pode ser um passo mais forte que o de ontem.",
      "Automação exige paciência — tédio faz parte do progresso.",
      "Meça-se, não julgue; dados são seu mapa.",
      "O ritmo pode subir perto da meta — proteja respiração e compasso.",
      "Uma frase de intenção alivia o resto do dia.",
      "Esta jornada não são 66 dias — é hábito reescolhido todo dia.",
      "Aparecer hoje já é uma vitória significativa.",
    ],
  },
};

const coachNotes = {
  tr: {
    day7: "Bir hafta tamam. Çapa yerine oturdu — her gün biraz daha az zorlanıyorsun.",
    day14: "İki hafta geride. Beyinde yeni yollar şekilleniyor; fark etmesen bile ilerliyorsun.",
    day22: "Kritik eşik: buraya kadar gelenlerin çoğu bitiriyor. Sen de oradasın.",
    day30: "30 gün. Artık 'yaptın mı?' değil, 'kim oluyorsun?' sorusu geçerli.",
    day44: "Faz 2 bitti. Çoğu gün artık seçim gibi değil, akış gibi hissedilir.",
    day66: "66 gün. Bu ritim artık sende — kimse alamaz, sen inşa ettin.",
  },
  en: {
    day7: "One week done. The anchor is settling — each day feels a little easier.",
    day14: "Two weeks behind you. New pathways are forming; progress continues even when you don't feel it.",
    day22: "Critical threshold: most people who reach here finish. You're here.",
    day30: "30 days. The question isn't 'did you do it?' — it's 'who are you becoming?'",
    day44: "Phase 2 complete. Most days no longer feel like a choice — more like flow.",
    day66: "66 days. This rhythm is yours now — no one can take what you built.",
  },
  "pt-BR": {
    day7: "Uma semana completa. A âncora assentou — cada dia pesa um pouco menos.",
    day14: "Duas semanas. Novos caminhos se formam; o progresso continua mesmo sem você sentir.",
    day22: "Limite crítico: a maioria que chega aqui termina. Você está aqui.",
    day30: "30 dias. A pergunta não é 'fez?' — é 'quem você está se tornando?'",
    day44: "Fase 2 concluída. A maioria dos dias não parece escolha — parece fluxo.",
    day66: "66 dias. Este ritmo é seu agora — ninguém tira o que você construiu.",
  },
};

const dailyPrinciplesPatch = {
  tr: {
    "1": {
      principle: "Başlamak, mükemmelleşmekten yüzlerce kez daha önemlidir.",
      science: "Başladığın iş zihinde açık kalır (Zeigarnik) — kapatma dürtüsü seni tekrar masaya getirir.",
      action: "Alışkanlığı bugünün en küçük sürümüne indir; sadece bir kez başlat.",
    },
    "2": {
      principle: "Motivasyon bir duygudur; duygular geçer, sistem ve çapa kalır.",
      science: "Öz-Belirleme Kuramı: sürdürülebilir davranış özerklik ve anlam ister (Deci & Ryan).",
      action: "Nedenini 10 saniyede yaz, sonra sadece tetik anında başla.",
    },
    "3": {
      principle: "Beyin mükemmel hisle değil, tekrarla öğrenir.",
      science: "Hebb kuralı: birlikte ateşleyen nöronlar birbirine bağlanır — her çapa tekrarı yolu güçlendirir.",
      action: "Aynı çapayı aynı saatte bir kez daha yap.",
    },
    "4": {
      principle: "Küçük davranış, büyük direnci sessizce aşar.",
      science: "Uygulama niyetleri, planlı tetik-eylem çiftlerini iki kat daha güvenilir kılar (Gollwitzer).",
      action: "If-then cümlesini yüksek sesle söyle: 'X olunca, Y yapacağım.'",
    },
    "5": {
      principle: "Dağılmak içgüdü; çözüm ortamı tasarlamaktır.",
      science: "Sürtünme azalınca zorluk düşer — davranış tasarımı iradeden verimli (Thaler & Sunstein).",
      action: "Alet veya hazırlığı bu akşam 30 saniyede önceden hazırla.",
    },
    "6": {
      principle: "Kimlik önce bir cümle, sonra tekrar eden hareketle büyür.",
      science: "Öz-şema: tutarlı davranış hikâyesi kimliği pekiştirir (Bem / kimlik yansıması).",
      action: "Bugün şunu söyle: 'Ben başlayan biriyim' — ardından tek tekrar.",
    },
    "7": {
      principle: "Yedi gün, beyne yeni bir yol açmak için güçlü bir ilk sinyaldir.",
      science: "Sinaptik plastisite tekrarla güçlenir; süre kişiden kişiye değişir (Lally).",
      action: "İlk günkü mini sürüme dön ve bir tur daha tamamla.",
    },
    "8": {
      principle: "Vazgeçme düşüncesi, beynin eski yolu korumasıdır — normal ve geçicidir.",
      science: "Eski alışkanlık: bazal ganglion-dopamin döngüsü; yeni yol henüz ince (araştırma özeti).",
      action: "Dünkü tek kazanımı sesli söyle — pozitif ayrıntı yeni yolu besler.",
    },
    "9": {
      principle: "Bazen en iyi ödül, sadece 'bitirdim' hissidir.",
      science: "Küçük tamamlama ödülleri dopamini dengeli pekiştirir; abartı iç motivasyonu zayıflatır.",
      action: "Tamamladıktan hemen sonra minik, sağlıklı bir 'işaret ödülü' ver.",
    },
    "10": {
      principle: "İstikrar, yoğunluktan daha güvenilirdir.",
      science: "Başlama eşiği: küçük tekrar büyüme için yeter; atlama motivasyonu kırar.",
      action: "Süre veya hacim yerine sadece 'bugün yaptım mı?' kutusuna odaklan.",
    },
    "11": {
      principle: "Zihin dağılsa bile tek tekrar günü kurtarır.",
      science: "Bilişsel yük doluyken prosedürel bellek baskılanır — mini sürüm yükü azaltır.",
      action: "Bugün en küçük sürümü seç; varlık, mükemmellikten önce gelir.",
    },
    "12": {
      principle: "Aynı çapa, aynı saat — desen tanınmaya başlar.",
      science: "Tekrar, prosedürel öğrenmeyi güçlendirir; 21 gün sihir değil, sinyal birikimi (Lally).",
      action: "Çapayı değiştirme; sadece bir kez daha aynı noktada başla.",
    },
    "13": {
      principle: "İki haftaya bir adım: sabır, hızdan değerlidir.",
      science: "Otomatiklik eğrisi yavaş ve dalgalıdır — sıkıcılık sürecin parçası (Lally, 2009).",
      action: "Bugün sadece görünür ol; süreyi değil varlığı işaretle.",
    },
    "14": {
      principle: "On dört gün: artık deneme değil, günlük bir iz bırakıyorsun.",
      science: "Öz-takip ve kayıt, davranışı anlamlı ölçüde iyileştirir (Harkin meta-analizi).",
      action: "Bugünkü tekrarı işaretle — veri, ilerlemenin haritasıdır.",
    },
  },
  en: {
    "1": {
      principle: "Starting is hundreds of times more important than perfecting.",
      science: "Started tasks stay open in the mind (Zeigarnik) — the urge to close pulls you back.",
      action: "Shrink the habit to today's smallest version; start just once.",
    },
    "2": {
      principle: "Motivation is a feeling; feelings pass, your system and anchor remain.",
      science: "Self-Determination Theory: sustainable behavior needs autonomy and meaning (Deci & Ryan).",
      action: "Write your why in 10 seconds, then start only at the trigger moment.",
    },
    "3": {
      principle: "The brain learns through repetition, not through feeling perfect.",
      science: "Hebb's rule: neurons that fire together wire together — each anchor rep strengthens the path.",
      action: "Repeat the same anchor at the same time once more.",
    },
    "4": {
      principle: "Small behavior quietly beats big resistance.",
      science: "Implementation intentions make planned trigger-action pairs far more reliable (Gollwitzer).",
      action: "Say your if-then aloud: 'When X happens, I will do Y.'",
    },
    "5": {
      principle: "Distraction is instinct; the answer is designing your environment.",
      science: "Less friction means less difficulty — behavior design beats willpower (Thaler & Sunstein).",
      action: "Prep tools or setup tonight in 30 seconds.",
    },
    "6": {
      principle: "Identity starts as a sentence, then grows through repeated action.",
      science: "Self-schema: a consistent behavior story reinforces identity (BEM / identity reflection).",
      action: "Say today: 'I am someone who starts' — then do one rep.",
    },
    "7": {
      principle: "Seven days is a strong first signal for the brain to open a new path.",
      science: "Synaptic plasticity strengthens with repetition; duration varies by person (Lally).",
      action: "Return to day-one's mini version and complete one more round.",
    },
    "8": {
      principle: "The urge to quit is the old path defending itself — normal and temporary.",
      science: "Old habit: basal ganglia-dopamine loop; the new route is still thin (habit research).",
      action: "Say one win from yesterday aloud — positive detail feeds the new path.",
    },
    "9": {
      principle: "Sometimes the best reward is simply the 'I finished' feeling.",
      science: "Small completion rewards reinforce dopamine balance; excess weakens intrinsic drive.",
      action: "Give yourself a tiny, healthy 'marker reward' right after finishing.",
    },
    "10": {
      principle: "Consistency is more reliable than intensity.",
      science: "Starting threshold: small reps are enough for growth; skipping breaks motivation.",
      action: "Focus on 'did I show up today?' not duration or volume.",
    },
    "11": {
      principle: "Even one rep saves the day when the mind wanders.",
      science: "When cognitive load is high, procedural memory is suppressed — mini version lowers load.",
      action: "Choose today's smallest version; presence before perfection.",
    },
    "12": {
      principle: "Same anchor, same time — the pattern starts to be recognized.",
      science: "Repetition strengthens procedural learning; 21 days isn't magic, it's signal accumulation (Lally).",
      action: "Don't change the anchor; start once more at the same point.",
    },
    "13": {
      principle: "One step from two weeks — patience beats speed.",
      science: "The automaticity curve is slow and wavy — boredom is part of the process (Lally, 2009).",
      action: "Just be visible today; mark presence, not duration.",
    },
    "14": {
      principle: "Fourteen days: you're leaving a daily trace, not running a trial.",
      science: "Self-monitoring and tracking meaningfully improve behavior (Harkin meta-analysis).",
      action: "Mark today's rep — data is your progress map.",
    },
  },
  "pt-BR": {
    "1": {
      principle: "Começar é centenas de vezes mais importante que aperfeiçoar.",
      science: "Tarefas iniciadas ficam abertas na mente (Zeigarnik) — a vontade de fechar te puxa de volta.",
      action: "Encolha o hábito para a menor versão de hoje; comece só uma vez.",
    },
    "2": {
      principle: "Motivação é sentimento; sentimentos passam, sistema e âncora ficam.",
      science: "Teoria da Autodeterminação: comportamento sustentável precisa de autonomia e significado (Deci & Ryan).",
      action: "Escreva seu porquê em 10 segundos, depois comece só no gatilho.",
    },
    "3": {
      principle: "O cérebro aprende com repetição, não com sensação de perfeição.",
      science: "Regra de Hebb: neurônios que disparam juntos se conectam — cada rep da âncora fortalece o caminho.",
      action: "Repita a mesma âncora no mesmo horário mais uma vez.",
    },
    "4": {
      principle: "Comportamento pequeno vence resistência grande em silêncio.",
      science: "Intenções de implementação tornam pares gatilho-ação muito mais confiáveis (Gollwitzer).",
      action: "Diga seu se-então em voz alta: 'Quando X, farei Y.'",
    },
    "5": {
      principle: "Distração é instinto; a resposta é desenhar o ambiente.",
      science: "Menos atrito, menos dificuldade — design comportamental vence força de vontade (Thaler & Sunstein).",
      action: "Prepare ferramentas ou setup hoje à noite em 30 segundos.",
    },
    "6": {
      principle: "Identidade começa como frase, depois cresce com ação repetida.",
      science: "Autoesquema: história consistente de comportamento reforça identidade (BEM / reflexão de identidade).",
      action: "Diga hoje: 'Sou alguém que começa' — depois uma rep.",
    },
    "7": {
      principle: "Sete dias é um forte primeiro sinal para o cérebro abrir um novo caminho.",
      science: "Plasticidade sináptica fortalece com repetição; duração varia por pessoa (Lally).",
      action: "Volte à mini versão do dia um e complete mais uma rodada.",
    },
    "8": {
      principle: "Vontade de desistir é o caminho antigo se defendendo — normal e temporário.",
      science: "Hábito antigo: loop gânglios da base-dopamina; rota nova ainda fina (pesquisa de hábitos).",
      action: "Diga uma vitória de ontem em voz alta — detalhe positivo alimenta o novo caminho.",
    },
    "9": {
      principle: "Às vezes a melhor recompensa é só o sentimento de 'terminei'.",
      science: "Pequenas recompensas de conclusão equilibram dopamina; excesso enfraquece motivação interna.",
      action: "Dê uma 'recompensa marcador' minúscula e saudável logo após terminar.",
    },
    "10": {
      principle: "Consistência é mais confiável que intensidade.",
      science: "Limiar de início: reps pequenas bastam para crescimento; pular quebra motivação.",
      action: "Foque em 'apareci hoje?' não em duração ou volume.",
    },
    "11": {
      principle: "Uma rep salva o dia quando a mente dispersa.",
      science: "Com carga cognitiva alta, memória procedural é suprimida — mini versão reduz carga.",
      action: "Escolha a menor versão de hoje; presença antes de perfeição.",
    },
    "12": {
      principle: "Mesma âncora, mesmo horário — o padrão começa a ser reconhecido.",
      science: "Repetição fortalece aprendizado procedural; 21 dias não é mágica, é acúmulo de sinal (Lally).",
      action: "Não mude a âncora; comece mais uma vez no mesmo ponto.",
    },
    "13": {
      principle: "Um passo das duas semanas — paciência vence velocidade.",
      science: "Curva de automaticidade é lenta e ondulada — tédio faz parte do processo (Lally, 2009).",
      action: "Só seja visível hoje; marque presença, não duração.",
    },
    "14": {
      principle: "Quatorze dias: você deixa um rastro diário, não um teste.",
      science: "Autorregistro e acompanhamento melhoram comportamento de forma significativa (meta-análise Harkin).",
      action: "Marque a rep de hoje — dados são seu mapa de progresso.",
    },
  },
};

function patchLocale(file, langKey) {
  const raw = fs.readFileSync(file, "utf8");
  const data = JSON.parse(raw);

  data.journeyMoments = journeyMoments[langKey];
  data.coachNotes = coachNotes[langKey];

  for (const [day, fields] of Object.entries(dailyPrinciplesPatch[langKey])) {
    if (!data.dailyPrinciples[day]) data.dailyPrinciples[day] = {};
    Object.assign(data.dailyPrinciples[day], fields);
  }

  fs.writeFileSync(file, JSON.stringify(data, null, 2) + "\n", "utf8");
  console.log("patched", path.basename(file));
}

patchLocale(path.join(localesDir, "tr.json"), "tr");
patchLocale(path.join(localesDir, "en.json"), "en");
patchLocale(path.join(localesDir, "pt-BR.json"), "pt-BR");
