/** Push notification copy pools — tr / en / pt-BR */

const tr = {
  habitFallback: "alışkanlığın",
  phase: {
    "1": "Kuruluş",
    "2": "Pekiştirme",
    "3": "Otomatikleşme",
  },
  morning: {
    early: [
      {
        title: "Gün {{day}} — Beyin yeni yol açıyor",
        body: "{{habit}} için bugün kartındaki tek net hareketi seç.",
        bodyPlanned: "{{habit}} için bugün kartındaki tek net hareketi seç. Planın: {{plan}}.",
      },
      {
        title: "Gün {{day}} — İlk izler",
        body: "{{habit}}: Çapa + Bugün kartındaki mikro-adım. Küçük ama gerçek.",
        bodyPlanned: "Planın hazır: {{plan}}. {{habit}} için çapana dokun, sonra tek hamle.",
      },
      {
        title: "Gün {{day}} — Kimlik oyu başlıyor",
        body: '"{{habit}} yapan biri" olarak bugün bir oy daha. Kartı aç, işaretle.',
        bodyPlanned: "{{plan}} — {{habit}} yolunda ilk günlerde netlik kazandırır.",
      },
    ],
    day66: {
      title: "66 gün tamamlandı 🎉",
      body: "{{habit}} artık kim olduğunun parçası. Yapı her zaman burada.",
    },
    milestones: {
      "7": {
        title: "7 günlük kuruluş 🌱",
        body: "{{habit}}: İlk hafta tamamlandı. Beyin yeni bir deseni fark etmeye başladı. Devam et.",
      },
      "14": {
        title: "2. hafta — Örüntü kuruluyor",
        body: "{{habit}} için 14 gün. Nöronal iz güçleniyor — bugün de tekrar yeter.",
      },
      "21": {
        title: "21 gün — Kuruluş fazı bitiyor",
        body: "{{habit}}: 22. günden itibaren pekiştirme başlıyor. Bugün kartın var — küçük ama net bir adım.",
      },
      "23": {
        title: "Pekiştirme fazına geçtin",
        body: "{{habit}} artık ikinci fazda. Alışkanlık tekrarda oturuyor — bugün de devam.",
      },
      "30": {
        title: "30 gün — Yarı yoldasın 🎯",
        body: "{{habit}}: 30 günlük yolculuk. Beyin artık bu deseni biliyor. {{daysLeft}} gün daha.",
      },
      "44": {
        title: "Pekiştirme fazı tamamlandı",
        body: "{{habit}}: Son faza giriyorsun. Bugünden itibaren otomatikleşme başlıyor — devam et.",
      },
      "45": {
        title: "Son faz: Otomatikleşme 🚀",
        body: "{{habit}}: Seçimler alışkanlığa dönüşüyor. {{daysLeft}} gün daha — bugün kartını aç.",
      },
      "60": {
        title: "60 gün — Bitiş çizgisi görünüyor",
        body: "{{habit}}: {{daysLeft}} gün kaldı. Bu yolculuk kimliğinin parçası haline geliyor.",
      },
    },
    green: [
      { title: "Gün {{day}} — {{streak}} gün üst üste 🔥", body: "{{habit}} yolunda gidiyorsun. Bugün de küçük adımını seç.", bodyPlanned: "Dün planladığın: {{plan}}. Hadi bir adım daha." },
      { title: "{{streak}} günlük seri devam ediyor", body: "{{habit}}: Bugün kartındaki tek hareketi yap, gün tamam." },
      { title: "Gün {{day}} — Kas güçleniyor", body: "{{habit}} için bugün de bir mikro-adım yeter.", bodyPlanned: "Planın: {{plan}}. {{habit}} için hadi başla." },
      { title: "Çapa + tek hareket", body: "{{habit}}: Önce çapanı yap, sonra karttaki tek adımı seç — 30 saniye." },
      { title: "Gün {{day}} — Kimlik oyu", body: '"{{habit}} yapan biri olarak bugün bir oy daha": Kartı aç, işaretle.' },
      { title: "Sabah ritmi", body: "{{habit}}: Küçük sürümle başla — mükemmellik bekleme." },
      { title: "{{phase}} fazındasın", body: "{{habit}} için beyin bu fazda deseni oturuyor. Bugün de tekrar — kısa bile olsa." },
      { title: "Tekrar = iz", body: "Beyin her tekrarda daha az enerji harcıyor. {{habit}} için bugün bir iz daha bırak." },
      { title: "Gün {{day}} — {{daysLeft}} gün kaldı", body: "{{habit}} için {{daysLeft}} gün daha. Bugün kartını aç, devam et." },
      { title: "Momentum gerçek", body: "{{streak}} günlük seri beyninde bir iz. {{habit}} için bugün de küçük ama net bir adım." },
      { title: "Gün {{day}} — İyi haber", body: "{{habit}} yapan birinin sabahı. Kart açık — tek adımın hazır." },
      { title: "Desen oturuyor", body: "{{phase}} fazında {{habit}} tekrarı beyne tanıdık geliyor. Bugün de aynı küçük adım." },
    ],
    greenHighAuto: [
      { title: "Otomatiklik yükseliyor", body: "Son günlerde otomatiklik ortalaman {{autoAvg}}/10. {{habit}} için bugün de aynı küçük adım." },
      { title: "Beyin yolu ezberledi", body: "{{habit}}: {{autoAvg}}/10 otomatiklik — seçim daha az enerji harcıyor. Devam et." },
      { title: "Akışa yaklaşıyorsun", body: "{{habit}} artık daha az çaba istiyor ({{autoAvg}}/10). Bugün kartı aç, ritmi koru." },
      { title: "Gün {{day}} — Alışkanlık oturuyor", body: "{{autoAvg}}/10 otomatiklik skoru güçlü. {{habit}} için bugün de tek tekrar yeter." },
      { title: "Kimlik sinyali", body: "{{habit}} yapan biri olarak artık daha az düşünüyorsun ({{autoAvg}}/10). Bugün de bir oy." },
      { title: "Son faz yaklaşıyor", body: "Otomatiklik {{autoAvg}}/10 — {{habit}} seçimi bedene yaklaşıyor. Küçük adım yeter." },
      { title: "Ritim oturdu", body: "{{habit}}: Beyin bu yolu artık tanıyor ({{autoAvg}}/10). Bugün kartındaki hamleyi seç." },
      { title: "Az çaba, çok iz", body: "{{autoAvg}}/10 otomatiklik — {{habit}} için bugün de en küçük sürüm bile güçlü bir sinyal." },
    ],
    greenLowAuto: [
      { title: "Hâlâ emek veriyorsun — normal", body: "Otomatiklik {{autoAvg}}/10; {{habit}} henüz tam oturmadı. Küçük adım yine de iz bırakır." },
      { title: "Çaba = yatırım", body: "{{habit}} için bilinçli seçim yapıyorsun ({{autoAvg}}/10). Bugün kartı aç — tekrar kası güçlenir." },
      { title: "Gün {{day}} — Sabır fazı", body: "{{phase}} fazında {{autoAvg}}/10 otomatiklik beklenen. {{habit}}: Küçük sürüm yeter." },
      { title: "Henüz otomatik değil", body: "{{autoAvg}}/10 — {{habit}} hâlâ bilinçli bir seçim. Bugün de tek hamle deseni pekiştirir." },
      { title: "Beyin öğreniyor", body: "Otomatiklik {{autoAvg}}/10; her tekrar {{habit}} yolunu biraz daha tanıdık kılar. Devam et." },
      { title: "Küçük adım, büyük etki", body: "{{habit}}: {{autoAvg}}/10 otomatiklik olsa da bugün karttaki mikro-adım ilerlemedir." },
      { title: "Emekli günler geçer", body: "{{autoAvg}}/10 — zor hissetmek normal. {{habit}} için en küçük sürüm bile sayılır." },
      { title: "Tekrar kası çalışıyor", body: "{{habit}} henüz akışta değil ({{autoAvg}}/10). Bugün çapa + tek hareket yeter." },
    ],
    yellow: [
      { title: "Gün {{day}} — Kayma noktası", body: "{{habit}}: Son günler zorladı ama bugün küçük sürümü seçersen yeterli." },
      { title: "Dünü bırak, bugüne bak", body: "{{habit}} için en küçük versiyonu bile say. Bugün kartını aç." },
      { title: "Gün {{day}} — Tek adım yeter", body: "Motivasyonu bekleme. {{habit}} kartındaki net eylemi seç — 10 saniye bile sayılır." },
      { title: "Kayma haftası değil", body: "{{habit}}: Dün zor olsa da bugün 2 dk sürüm yeter — seri yeniden başlar." },
      { title: "Beyin eski yolu hatırlıyor", body: "1 gün ara normal. {{habit}} için kartı aç, en küçük hareketi işaretle." },
      { title: "Mükemmellik tuzağı", body: "{{habit}}: Büyük olmak zorunda değil. 2 dk bile bu gün yaptım yapar." },
      { title: "{{phase}} fazında çatlak normal", body: "Orta fazdaki düşüş çoğu zaman motivasyon eksikliği değil — alışkanlık henüz otomatik değil. {{habit}} için bugün de bir adım." },
      { title: "Seri yeniden başlar", body: "{{habit}}: Bugün kartı en küçük sürümü sunar — tamamlamak değil başlamak.", bodyPlanned: "Planın: {{plan}}. {{habit}} için hâlâ vakit var." },
      { title: "Kimlik sorusu", body: '"{{habit}} yapan biri bugün ne yapar?" — Kartı aç, küçük ama gerçek bir adım seç.' },
      { title: "Gün {{day}} — Yön seçimi", body: "{{habit}} için bugün tam yapmak zorunda değilsin. Yalnızca yönünü seç." },
      { title: "Süreksizlik sinyali", body: "{{habit}}: Bir gün kayma deseni kırmaz — bugün küçük adımla yönü geri al." },
      { title: "Yeniden hizalan", body: "{{phase}} fazında {{habit}} için bugün tek net hamle yeter. Kart açık." },
    ],
    red: [
      { title: "Geri dönüş günü", body: "{{misses}} gün ara verdikten sonra geri dönmek de yolculuğun parçası. {{habit}} için bugün en küçük adım yeter." },
      { title: "Beynin hâlâ bu yolu biliyor", body: "{{habit}}: Araların ardından geri dönmek sistemin parçası. Bugün kartını aç." },
      { title: "Düşmek yolculuğun parçası", body: "{{habit}} yapan biri düştüğünde kalkar. En küçük sürümle başla — cezasız." },
      { title: "Geri dönüş modu", body: "{{habit}}: Önce ayağa kalk, sonra tek mikro adım — check-in sonra gelir." },
      { title: "Yolculuk devam ediyor", body: "{{misses}} gün ara geri dönüşü engellemez. {{habit}} kartını aç — en küçük sürüm bile hak ediyor." },
      { title: "Sıfırdan değil, devam", body: "{{habit}}: Ara verince sıfıra düşmezsin — birikim hâlâ orada. Bugün kartı açmak yeter." },
      { title: "Toparlanma da alışkanlık", body: "{{habit}}: En başarılı yolculuklar düzgün değil, dayanıklı olanlardır. Bugün devam." },
      { title: "Bugün bir adım at", body: "{{habit}}: Kartı aç, tek hareketi işaretle — bu yeter.", bodyPlanned: "Planın bekliyor: {{plan}}. Küçük de olsa {{habit}} için bugün." },
      { title: "İzin kendine verdin", body: "Birkaç gün ara vermek insani. {{habit}} için bugün geri dönmek yeterli bir seçim." },
      { title: "Gün {{day}} — Yeniden başla", body: "{{habit}}: Seri bitmiş olabilir ama yolculuk devam ediyor. Bugün küçük ama gerçek bir adım." },
      { title: "{{daysLeft}} gün hâlâ önde", body: "66 günlük yolun büyük kısmı devam ediyor. {{habit}} için bugün geri dön." },
      { title: "Kimlik oyu", body: "{{habit}}: Aralar geçici, alışkanlık kalıcı. Bugün kimliğin için bir oy daha." },
    ],
  },
  evening: {
    gentle: [
      { title: "Gün bitmeden: Bugün kartı", body: "{{habit}} için henüz hareket yok. En küçük sürüm bile yeter." },
      { title: "Son tur", body: "{{habit}}: Bugün kartındaki mikro-adımı seç — 10 saniye bile işe yarar." },
      { title: "2 dakika kuralı", body: "{{habit}} için en küçük sürümü seç — tamamlamak değil, başlamak." },
      { title: "Gün kapanmadan", body: "{{habit}}: Kartı aç, tek hareketi işaretle.", bodyPlanned: "Planın: {{plan}}. {{habit}} için hâlâ vakit var." },
      { title: "Bugün hâlâ sayılabilir", body: "{{habit}}: Gün bitmeden küçük de olsa bir hareket — akşam check-in yap." },
      { title: "Akşam ritmi", body: "{{habit}} için birkaç dakika kaldı. Kartı aç, ne kadar küçük olursa olsun seç." },
      { title: "Bilgi değil, tekrar", body: "Beyin enerjiyi yalnızca deneyimle öğrenir. {{habit}}: Bu akşam bir tekrar daha." },
      { title: "Gün {{day}} — Gece yarısından önce", body: "{{habit}}: Bugün en küçük sürümü yap. Yarın planlamak için de kart açık." },
      { title: "Akşam hatırlatması", body: "{{habit}}: Gün geçmeden tek hareket — çok az da olsa yeterli.", bodyPlanned: "{{plan}} hâlâ bekliyor. {{habit}} için son tur." },
      { title: "Gün sonu bilançosu", body: "{{habit}}: Bugün henüz yok. Küçük ama gerçek bir adımla bitir." },
      { title: "Çapa + mikro-adım", body: "{{habit}}: Akşam çapana dokun, sonra karttaki en küçük hamleyi seç." },
      { title: "Henüz geç değil", body: "Gün {{day}} — {{habit}} için tek net adım hâlâ mümkün. Küçült, başla." },
    ],
    gentleFirstWeek: [
      { title: "İlk hafta — Bugün kartı", body: "Gün {{day}}: {{habit}} için henüz vakit var. En küçük sürüm yeter — cezasız." },
      { title: "Kuruluş haftası", body: "{{habit}}: İlk 7 günde görünürlük mükemmellikten önemli. Kartı aç." },
      { title: "Gün {{day}} — Son şans değil", body: "{{habit}} için bu akşam tek mikro-adım bile desen kurar." },
      { title: "Yeni yol, yumuşak tempo", body: "Gün {{day}} — {{habit}}: Beyin henüz öğreniyor. Küçük adım yeter." },
      { title: "Akşam çapası", body: "{{habit}}: İlk haftada çapa + kart = güçlü başlangıç. Hâlâ vakit var." },
      { title: "Gün bitmeden", body: "{{habit}} için gün {{day}}. Henüz hareket yoksa en küçük sürümü seç." },
    ],
    urgent: [
      { title: "Seri kırılmak üzere ⚠️", body: "{{streak}} günlük serinin devam etmesi için {{habit}}: bugün en küçük adımı yap." },
      { title: "Bugün hâlâ sayılabilir", body: "{{habit}}: Motivasyonu bekleme — kartı aç, tek hareketi işaretle." },
      { title: "{{streak}} günlük seri", body: "Bugün de {{habit}} için en küçük adım — seri devam etsin." },
      { title: "Akşam çapası", body: "{{habit}}: Çapanı hatırla, sonra karttaki tek hareketi seç." },
      { title: "Gece yarısından önce", body: "{{habit}}: Seri {{streak}} gün. Bugün de küçük ama gerçek bir adım." },
      { title: "Son dakika fırsatı", body: "{{habit}}: Bugün kartını aç — 2 dakika yeter, seri kurtulur.", bodyPlanned: "Sabah planladığın: {{plan}}. Hâlâ mümkün." },
      { title: "Küçük ama gerçek", body: "{{streak}} gün biriktirdin. {{habit}}: Bugün de en küçük sürümle serini koru." },
      { title: "Akşam müdahalesi", body: "{{habit}}: Büyük bir adım değil, sadece bugünkü küçük tekrar — seri devam ediyor." },
      { title: "Bir oy daha", body: "{{habit}} yapan biri olarak bugün son bir oy: kartı aç, işaretle." },
      { title: "Gün bitmeden karar", body: "{{habit}}: Seri {{streak}} gün. Bugün 1 küçük adım + check-in = yeterli." },
      { title: "Seri koruması", body: "{{streak}} günlük iz — {{habit}} için bu akşam tek hamle yeter." },
      { title: "Streak modu", body: "{{habit}}: {{streak}} gün üst üste. Bugün küçült, yap, işaretle." },
    ],
    recovery: [
      { title: "Geri dönüş fırsatı", body: "{{habit}}: Bugün yapabilirsen seri yeniden başlar. Tek küçük hareket yeter." },
      { title: "Düşmek yolun parçası", body: "{{habit}} yapan biri bugün kartını açar. Cezasız — yalnızca tek adım." },
      { title: "Yeniden başlat", body: "{{habit}}: Önce mikro adım, sonra check-in — sıra önemli." },
      { title: "Bu gece sayılır", body: "Kaçırdığın günlerin ardından tek küçük hareket {{habit}} yolunu açık tutar." },
      { title: "Sıfırdan değil, devam", body: "{{habit}}: Birkaç gün ara verdikten sonra geri dönmek de bir seçim. Bugün kartını aç." },
      { title: "Beyin bu yolu biliyor", body: "{{habit}}: Aradan sonra geri dönmek beyne tanıdık geliyor — en küçük sürümle başla." },
      { title: "Toparlanma anı", body: "{{habit}}: Bu akşam tek küçük hareket bile yolculuğun devam ettiğini gösterir." },
      { title: "İzin verdin, şimdi dön", body: "{{habit}}: Birkaç günlük ara bitti. Bugün küçük ama gerçek bir adımla.", bodyPlanned: "Planın: {{plan}}. {{habit}}: Bu akşam geri dön." },
      { title: "Yolculuk devam ediyor", body: "Mükemmel seri değil, uzun soluk yolculuk önemli. {{habit}}: Bu akşam bir adım daha." },
      { title: "Gece yarısından önce", body: "{{habit}}: Bugün hâlâ mümkün. En küçük sürümle de olsa — bu gece sayılır." },
      { title: "{{misses}} gün ara — hâlâ erken", body: "{{habit}} kartını aç — küçük ama gerçek bir adım yolculuğu açık tutar." },
      { title: "Geri dönüş modu", body: "{{habit}}: Toparlanma da sistemin parçası. Bu akşam tek hamle yeter." },
    ],
    highEffort: [
      { title: "Zor günler — küçült", body: "{{habit}}: Son günler yüksek çaba istedi. Bu akşam en mini sürümü seç — yeter." },
      { title: "Ölçekleme önerisi", body: "Bugün {{habit}} için 2 dk sürüm bile sayılır. Kartı aç, küçült, devam et." },
      { title: "Emek fazı geçici", body: "{{habit}} henüz zor geliyor — normal. Bu akşam en küçük hamle yeter." },
      { title: "Yükü hafiflet", body: "{{habit}}: Zorlandığın günlerde mini sürüm = akıllı seçim. Bugün kartı aç." },
      { title: "Dayanıklılık > mükemmellik", body: "{{habit}} için bu akşam en küçük adım bile yolculuğu korur." },
      { title: "Çaba sinyali", body: "Son günler {{habit}} için ağır geçtiyse bugün sadece çapa + 10 sn yeter." },
    ],
  },
  streak: {
    milestones: {
      "7": { title: "7 gün üst üste 🔥", body: "{{habit}}: İlk haftalık seri tamamlandı. Beyin yeni bir yol açıyor — devam et." },
      "14": { title: "14 gün seri! 🌱", body: "{{habit}}: 2 haftadır kesintisiz. Nöronal iz güçleniyor. Devam et." },
      "21": { title: "21 günlük seri 🏆", body: "{{habit}}: 3 hafta tamamlandı. Bu seri, kimliğinin bir parçası haline geliyor." },
      "30": { title: "30 günlük seri 🎯", body: "{{habit}}: Yarı yolda! 30 günlük seri bu alışkanlığın gerçek olduğunu gösteriyor." },
      "44": { title: "44 gün — Pekiştirme bitti 💪", body: "{{habit}}: Son faza giriyorsun. Bu seri otomatikleşmenin başlangıcı." },
      "60": { title: "60 günlük seri 🌟", body: "{{habit}}: {{daysLeft}} gün kaldı. Bu yolculuk kim olduğunun parçası haline geliyor." },
      "66": { title: "66 gün tamamlandı! 🎉", body: "{{habit}} artık kimliğinin parçası. Bu alışkanlık seni tanımlayanlardan biri." },
    },
    weekly: {
      title: "{{streak}} günlük seri 🔥",
      body: "{{habit}} yapan biri olarak {{streak}} günlük yolculuğun devam ediyor. Kimlik kazanımı gerçek.",
    },
    every5: {
      title: "{{streak}} gün serisi",
      body: "{{habit}}: {{streak}} günlük tekrar beyne iz bırakıyor. Bugün de devam.",
    },
  },
  recovery: [
    { title: "Geri dönme zamanı", body: "{{misses}} gün ara verdin. {{habit}}: Yolculuğun geri kalanı hâlâ senin. Bugün kartını aç." },
    { title: "Yolculuk devam ediyor", body: "{{misses}} günlük ara bir engel değil — toparlamak da bu yolculuğun parçası. {{habit}} için bugün küçük bir adım." },
    { title: "Sıfırdan değil, devam", body: "{{habit}}: {{misses}} gün ara birikim silmez. Beyin hâlâ bu yolu biliyor — bugün geri dön." },
    { title: "Geri dönmek de alışkanlık", body: "{{habit}}: Her düşüşten sonra geri dönmek kasını güçlendirir. Bugün kartını aç." },
    { title: "Toparlanma anı", body: "{{misses}} günden sonra tek küçük adım bile fark yaratır. {{habit}}: Bugün o adımı at." },
    { title: "Kaçırmak değil, devam", body: "Mükemmel değil, dayanıklı olana yolculuk ödül veriyor. {{habit}}: Bugün geri dön." },
    { title: "{{misses}} gün ara — hâlâ erken", body: "66 günlük yolun büyük kısmı önde. {{habit}} kartını aç — küçük ama gerçek bir adım." },
    { title: "Kimlik oyu", body: "{{habit}}: Aralar geçici, alışkanlık kalıcı. Bugün kimliğin için bir oy daha." },
    { title: "Beyin bekliyor", body: "{{misses}} gün ara sonrası {{habit}} yolu hâlâ açık. En küçük sürümle başla." },
    { title: "Toparlanma günü", body: "{{habit}}: {{misses}} gün kayıp seriyi sıfırlamaz — yolculuğu durdurmaz. Bugün dön." },
  ],
};

const en = {
  habitFallback: "your habit",
  phase: {
    "1": "Foundation",
    "2": "Reinforcement",
    "3": "Automation",
  },
  morning: {
    early: [
      {
        title: "Day {{day}} — Your brain is opening a new path",
        body: "For {{habit}}, pick the one clear move on today's card.",
        bodyPlanned: "For {{habit}}, pick the one clear move on today's card. Your plan: {{plan}}.",
      },
      {
        title: "Day {{day}} — First traces",
        body: "{{habit}}: Anchor + the micro-step on your Today card. Small but real.",
        bodyPlanned: "Your plan is ready: {{plan}}. Touch your anchor for {{habit}}, then one move.",
      },
      {
        title: "Day {{day}} — Identity vote begins",
        body: 'As someone who does {{habit}}, cast one more vote today. Open the card, mark it.',
        bodyPlanned: "{{plan}} — clarity in the early days helps {{habit}} stick.",
      },
    ],
    day66: {
      title: "66 days complete 🎉",
      body: "{{habit}} is now part of who you are. The structure is always here.",
    },
    milestones: {
      "7": {
        title: "7-day foundation 🌱",
        body: "{{habit}}: First week done. Your brain is starting to notice a new pattern. Keep going.",
      },
      "14": {
        title: "Week 2 — Pattern forming",
        body: "14 days of {{habit}}. The neural trace is strengthening — one repeat today is enough.",
      },
      "21": {
        title: "Day 21 — Foundation phase ending",
        body: "{{habit}}: Reinforcement starts on day 22. Your card is ready — one small, clear step.",
      },
      "23": {
        title: "You entered reinforcement",
        body: "{{habit}} is now in phase two. The habit settles through repetition — continue today.",
      },
      "30": {
        title: "Day 30 — Halfway there 🎯",
        body: "{{habit}}: 30 days in. Your brain knows this pattern now. {{daysLeft}} days to go.",
      },
      "44": {
        title: "Reinforcement phase complete",
        body: "{{habit}}: You're entering the final phase. Automation begins today — keep going.",
      },
      "45": {
        title: "Final phase: Automation 🚀",
        body: "{{habit}}: Choices are becoming habit. {{daysLeft}} days left — open your card today.",
      },
      "60": {
        title: "Day 60 — Finish line in sight",
        body: "{{habit}}: {{daysLeft}} days left. This journey is becoming part of your identity.",
      },
    },
    green: [
      { title: "Day {{day}} — {{streak}} days in a row 🔥", body: "You're on track with {{habit}}. Pick your small step today.", bodyPlanned: "You planned: {{plan}}. One more step." },
      { title: "{{streak}}-day streak continues", body: "{{habit}}: Do the one move on today's card — day done." },
      { title: "Day {{day}} — Muscle building", body: "One micro-step for {{habit}} today is enough.", bodyPlanned: "Your plan: {{plan}}. Time to start {{habit}}." },
      { title: "Anchor + one move", body: "{{habit}}: Do your anchor first, then pick the one step on the card — 30 seconds." },
      { title: "Day {{day}} — Identity vote", body: '"As someone who does {{habit}}, one more vote today": Open the card, mark it.' },
      { title: "Morning rhythm", body: "{{habit}}: Start with the smallest version — don't wait for perfection." },
      { title: "You're in {{phase}}", body: "In this phase, your brain is settling the pattern for {{habit}}. Repeat today — even briefly." },
      { title: "Repetition = trace", body: "Each repeat costs your brain less energy. Leave one more trace for {{habit}} today." },
      { title: "Day {{day}} — {{daysLeft}} days left", body: "{{daysLeft}} more days for {{habit}}. Open your card, keep going." },
      { title: "Momentum is real", body: "A {{streak}}-day streak is a trace in your brain. One small, clear step for {{habit}} today." },
      { title: "Day {{day}} — Good news", body: "A morning for someone who does {{habit}}. Card open — your one step is ready." },
      { title: "Pattern settling", body: "In {{phase}}, {{habit}} repetition feels more familiar. Same small step today." },
    ],
    greenHighAuto: [
      { title: "Automation rising", body: "Recent automation average: {{autoAvg}}/10. Same small step for {{habit}} today." },
      { title: "Brain knows the path", body: "{{habit}}: {{autoAvg}}/10 automation — the choice takes less energy. Keep going." },
      { title: "Approaching flow", body: "{{habit}} needs less effort now ({{autoAvg}}/10). Open the card, keep the rhythm." },
      { title: "Day {{day}} — Habit settling", body: "Strong automation score {{autoAvg}}/10. One repeat for {{habit}} today is enough." },
      { title: "Identity signal", body: "As someone who does {{habit}}, you think less now ({{autoAvg}}/10). One more vote today." },
      { title: "Final phase approaching", body: "Automation {{autoAvg}}/10 — {{habit}} choice is becoming bodily. Small step enough." },
      { title: "Rhythm locked in", body: "{{habit}}: Your brain recognizes this path ({{autoAvg}}/10). Pick the move on today's card." },
      { title: "Less effort, more trace", body: "{{autoAvg}}/10 automation — even the smallest version of {{habit}} is a strong signal today." },
    ],
    greenLowAuto: [
      { title: "Still effortful — that's normal", body: "Automation {{autoAvg}}/10; {{habit}} isn't automatic yet. A small step still leaves a trace." },
      { title: "Effort = investment", body: "You're choosing {{habit}} consciously ({{autoAvg}}/10). Open the card — the repeat muscle grows." },
      { title: "Day {{day}} — Patience phase", body: "In {{phase}}, {{autoAvg}}/10 automation is expected. {{habit}}: Smallest version is enough." },
      { title: "Not automatic yet", body: "{{autoAvg}}/10 — {{habit}} is still a conscious choice. One move today strengthens the pattern." },
      { title: "Brain is learning", body: "Automation {{autoAvg}}/10; each repeat makes the {{habit}} path more familiar. Continue." },
      { title: "Small step, big effect", body: "{{habit}}: At {{autoAvg}}/10 automation, today's micro-step on the card is progress." },
      { title: "Effortful days pass", body: "{{autoAvg}}/10 — feeling hard is normal. The smallest version of {{habit}} still counts." },
      { title: "Repeat muscle working", body: "{{habit}} isn't in flow yet ({{autoAvg}}/10). Anchor + one move today is enough." },
    ],
    yellow: [
      { title: "Day {{day}} — Drift point", body: "{{habit}}: Recent days were tough, but the smallest version today is enough." },
      { title: "Leave yesterday, look at today", body: "Even the tiniest version of {{habit}} counts. Open today's card." },
      { title: "Day {{day}} — One step is enough", body: "Don't wait for motivation. Pick the clear action on your {{habit}} card — 10 seconds counts." },
      { title: "Not a drift week", body: "{{habit}}: Yesterday was hard, but a 2-min version today restarts the streak." },
      { title: "Brain remembers the old path", body: "One day off is normal. Open the card for {{habit}}, mark the smallest move." },
      { title: "Perfection trap", body: "{{habit}}: It doesn't have to be big. Even 2 minutes makes today a 'done' day." },
      { title: "Cracks normal in {{phase}}", body: "Mid-phase dips are often not lack of motivation — the habit isn't automatic yet. One step for {{habit}} today." },
      { title: "Streak restarts", body: "{{habit}}: Today's card offers the smallest version — start, don't finish.", bodyPlanned: "Your plan: {{plan}}. Still time for {{habit}}." },
      { title: "Identity question", body: '"What would someone who does {{habit}} do today?" — Open the card, pick one small real step.' },
      { title: "Day {{day}} — Choose direction", body: "You don't have to do {{habit}} fully today. Just choose your direction." },
      { title: "Inconsistency signal", body: "{{habit}}: One missed day doesn't break the pattern — reclaim direction with a small step today." },
      { title: "Realign", body: "In {{phase}}, one clear move for {{habit}} today is enough. Card is open." },
    ],
    red: [
      { title: "Return day", body: "Coming back after {{misses}} days off is part of the journey. The smallest step for {{habit}} today is enough." },
      { title: "Your brain still knows this path", body: "{{habit}}: Returning after gaps is built into the system. Open your card today." },
      { title: "Falling is part of the journey", body: "Someone who does {{habit}} gets back up. Start with the smallest version — no guilt." },
      { title: "Return mode", body: "{{habit}}: Stand up first, then one micro-step — check-in comes after." },
      { title: "Journey continues", body: "{{misses}} days off don't block return. Open your {{habit}} card — the smallest version deserves it." },
      { title: "Not from zero, continue", body: "{{habit}}: A break doesn't reset you to zero — the buildup is still there. Opening the card is enough." },
      { title: "Recovery is also habit", body: "{{habit}}: The best journeys aren't smooth, they're resilient. Continue today." },
      { title: "Take one step today", body: "{{habit}}: Open the card, mark one move — that's enough.", bodyPlanned: "Your plan waits: {{plan}}. Even small, for {{habit}} today." },
      { title: "You gave yourself permission", body: "A few days off is human. Coming back to {{habit}} today is a good enough choice." },
      { title: "Day {{day}} — Start again", body: "{{habit}}: The streak may be gone but the journey continues. One small real step today." },
      { title: "{{daysLeft}} days still ahead", body: "Most of the 66-day path is still ahead. Come back to {{habit}} today." },
      { title: "Identity vote", body: "{{habit}}: Gaps are temporary, habit is lasting. One more vote for your identity today." },
    ],
  },
  evening: {
    gentle: [
      { title: "Before the day ends: Today card", body: "No movement yet for {{habit}}. The smallest version is enough." },
      { title: "Last round", body: "{{habit}}: Pick the micro-step on today's card — even 10 seconds works." },
      { title: "2-minute rule", body: "Pick the smallest version of {{habit}} — start, don't finish." },
      { title: "Before the day closes", body: "{{habit}}: Open the card, mark one move.", bodyPlanned: "Your plan: {{plan}}. Still time for {{habit}}." },
      { title: "Today still counts", body: "{{habit}}: One small move before the day ends — evening check-in after." },
      { title: "Evening rhythm", body: "A few minutes left for {{habit}}. Open the card, pick however small." },
      { title: "Not knowledge, repetition", body: "The brain only learns through experience. {{habit}}: One more repeat this evening." },
      { title: "Day {{day}} — Before midnight", body: "{{habit}}: Do the smallest version today. Card open for tomorrow's plan too." },
      { title: "Evening nudge", body: "{{habit}}: One move before the day passes — however small is enough.", bodyPlanned: "{{plan}} is still waiting. Last round for {{habit}}." },
      { title: "End-of-day balance", body: "{{habit}}: Not yet today. Finish with one small real step." },
      { title: "Anchor + micro-step", body: "{{habit}}: Touch your evening anchor, then pick the smallest move on the card." },
      { title: "Not too late yet", body: "Day {{day}} — one clear step for {{habit}} is still possible. Shrink it, start." },
    ],
    gentleFirstWeek: [
      { title: "First week — Today card", body: "Day {{day}}: Still time for {{habit}}. Smallest version is enough — no guilt." },
      { title: "Foundation week", body: "{{habit}}: In the first 7 days, visibility beats perfection. Open the card." },
      { title: "Day {{day}} — Not last chance", body: "One micro-step for {{habit}} this evening still builds the pattern." },
      { title: "New path, gentle pace", body: "Day {{day}} — {{habit}}: Brain is still learning. Small step is enough." },
      { title: "Evening anchor", body: "{{habit}}: In week one, anchor + card = strong start. Still time." },
      { title: "Before the day ends", body: "{{habit}} on day {{day}}. If no movement yet, pick the smallest version." },
    ],
    urgent: [
      { title: "Streak about to break ⚠️", body: "To keep your {{streak}}-day streak: {{habit}} — do the smallest step today." },
      { title: "Today still counts", body: "{{habit}}: Don't wait for motivation — open the card, mark one move." },
      { title: "{{streak}}-day streak", body: "Smallest step for {{habit}} today — keep the streak going." },
      { title: "Evening anchor", body: "{{habit}}: Remember your anchor, then pick the one move on the card." },
      { title: "Before midnight", body: "{{habit}}: Streak is {{streak}} days. One small real step today." },
      { title: "Last-minute window", body: "{{habit}}: Open today's card — 2 minutes saves the streak.", bodyPlanned: "You planned this morning: {{plan}}. Still possible." },
      { title: "Small but real", body: "You built {{streak}} days. {{habit}}: Smallest version today protects the streak." },
      { title: "Evening intervention", body: "{{habit}}: Not a big step — just today's small repeat — streak continues." },
      { title: "One more vote", body: "As someone who does {{habit}}, one last vote today: open the card, mark it." },
      { title: "Decision before day ends", body: "{{habit}}: Streak {{streak}} days. 1 small step + check-in = enough." },
      { title: "Streak protection", body: "{{streak}}-day trace — one move for {{habit}} this evening is enough." },
      { title: "Streak mode", body: "{{habit}}: {{streak}} days in a row. Shrink it, do it, mark it." },
    ],
    recovery: [
      { title: "Return opportunity", body: "{{habit}}: If you do it today, the streak restarts. One small move is enough." },
      { title: "Falling is part of the path", body: "Someone who does {{habit}} opens the card today. No guilt — just one step." },
      { title: "Restart", body: "{{habit}}: Micro-step first, check-in after — order matters." },
      { title: "Tonight counts", body: "After missed days, one small move keeps the {{habit}} path open." },
      { title: "Not from zero, continue", body: "{{habit}}: Coming back after a few days off is also a choice. Open your card today." },
      { title: "Brain knows this path", body: "{{habit}}: Returning feels familiar to the brain — start with the smallest version." },
      { title: "Recovery moment", body: "{{habit}}: One small move this evening shows the journey continues." },
      { title: "You paused, now return", body: "{{habit}}: A few days off is over. Today with one small real step.", bodyPlanned: "Your plan: {{plan}}. {{habit}}: Return this evening." },
      { title: "Journey continues", body: "Not a perfect streak — a long journey matters. {{habit}}: One more step this evening." },
      { title: "Before midnight", body: "{{habit}}: Still possible today. Even the smallest version — tonight counts." },
      { title: "{{misses}} days off — still early", body: "Open your {{habit}} card — one small real step keeps the journey open." },
      { title: "Return mode", body: "{{habit}}: Recovery is part of the system. One move this evening is enough." },
    ],
    highEffort: [
      { title: "Hard days — shrink it", body: "{{habit}}: Recent days took high effort. Pick the mini version this evening — enough." },
      { title: "Scaling suggestion", body: "Even a 2-min version of {{habit}} today counts. Open the card, shrink, continue." },
      { title: "Effort phase is temporary", body: "{{habit}} still feels hard — normal. Smallest move this evening is enough." },
      { title: "Lighten the load", body: "{{habit}}: On hard days, mini version = smart choice. Open the card today." },
      { title: "Resilience > perfection", body: "The smallest step for {{habit}} this evening still protects the journey." },
      { title: "Effort signal", body: "If recent days felt heavy for {{habit}}, today just anchor + 10 sec is enough." },
    ],
  },
  streak: {
    milestones: {
      "7": { title: "7 days in a row 🔥", body: "{{habit}}: First weekly streak complete. Your brain is opening a new path — keep going." },
      "14": { title: "14-day streak! 🌱", body: "{{habit}}: 2 weeks without a break. Neural trace strengthening. Continue." },
      "21": { title: "21-day streak 🏆", body: "{{habit}}: 3 weeks done. This streak is becoming part of your identity." },
      "30": { title: "30-day streak 🎯", body: "{{habit}}: Halfway! A 30-day streak shows this habit is real." },
      "44": { title: "44 days — Reinforcement done 💪", body: "{{habit}}: Entering the final phase. This streak is the start of automation." },
      "60": { title: "60-day streak 🌟", body: "{{habit}}: {{daysLeft}} days left. This journey is becoming who you are." },
      "66": { title: "66 days complete! 🎉", body: "{{habit}} is now part of your identity. One of the habits that defines you." },
    },
    weekly: {
      title: "{{streak}}-day streak 🔥",
      body: "As someone who does {{habit}}, your {{streak}}-day journey continues. Identity gain is real.",
    },
    every5: {
      title: "{{streak}}-day streak",
      body: "{{habit}}: {{streak}} days of repetition leave a trace in the brain. Continue today.",
    },
  },
  recovery: [
    { title: "Time to return", body: "You took {{misses}} days off. {{habit}}: The rest of the journey is still yours. Open your card today." },
    { title: "Journey continues", body: "{{misses}} days off isn't a blocker — recovery is part of this journey. One small step for {{habit}} today." },
    { title: "Not from zero, continue", body: "{{habit}}: {{misses}} days off doesn't erase buildup. Your brain still knows this path — return today." },
    { title: "Returning is also habit", body: "{{habit}}: Coming back after each fall strengthens the muscle. Open your card today." },
    { title: "Recovery moment", body: "After {{misses}} days, one small step makes a difference. {{habit}}: Take it today." },
    { title: "Not missing, continuing", body: "The journey rewards resilience, not perfection. {{habit}}: Return today." },
    { title: "{{misses}} days off — still early", body: "Most of the 66-day path is ahead. Open your {{habit}} card — one small real step." },
    { title: "Identity vote", body: "{{habit}}: Gaps are temporary, habit is lasting. One more vote for your identity today." },
    { title: "Brain is waiting", body: "After {{misses}} days off, the {{habit}} path is still open. Start with the smallest version." },
    { title: "Recovery day", body: "{{habit}}: {{misses}} days lost doesn't reset the journey. Return today." },
  ],
};

const ptBR = {
  habitFallback: "seu hábito",
  phase: {
    "1": "Fundação",
    "2": "Reforço",
    "3": "Automatização",
  },
  morning: {
    early: [
      {
        title: "Dia {{day}} — Seu cérebro abre um novo caminho",
        body: "Para {{habit}}, escolha o único movimento claro no cartão de Hoje.",
        bodyPlanned: "Para {{habit}}, escolha o único movimento claro no cartão de Hoje. Seu plano: {{plan}}.",
      },
      {
        title: "Dia {{day}} — Primeiros traços",
        body: "{{habit}}: Âncora + micro-passo no cartão Hoje. Pequeno, mas real.",
        bodyPlanned: "Seu plano está pronto: {{plan}}. Toque sua âncora para {{habit}}, depois um movimento.",
      },
      {
        title: "Dia {{day}} — Voto de identidade começa",
        body: 'Como alguém que faz {{habit}}, dê mais um voto hoje. Abra o cartão, marque.',
        bodyPlanned: "{{plan}} — clareza nos primeiros dias ajuda {{habit}} a fixar.",
      },
    ],
    day66: {
      title: "66 dias completos 🎉",
      body: "{{habit}} agora faz parte de quem você é. A estrutura está sempre aqui.",
    },
    milestones: {
      "7": {
        title: "7 dias de fundação 🌱",
        body: "{{habit}}: Primeira semana concluída. Seu cérebro começa a notar um novo padrão. Continue.",
      },
      "14": {
        title: "Semana 2 — Padrão se formando",
        body: "14 dias de {{habit}}. O traço neural fortalece — uma repetição hoje basta.",
      },
      "21": {
        title: "Dia 21 — Fase de fundação terminando",
        body: "{{habit}}: Reforço começa no dia 22. Seu cartão está pronto — um passo pequeno e claro.",
      },
      "23": {
        title: "Você entrou no reforço",
        body: "{{habit}} está na fase dois. O hábito se fixa pela repetição — continue hoje.",
      },
      "30": {
        title: "Dia 30 — Metade do caminho 🎯",
        body: "{{habit}}: 30 dias. Seu cérebro já conhece esse padrão. Faltam {{daysLeft}} dias.",
      },
      "44": {
        title: "Fase de reforço concluída",
        body: "{{habit}}: Você entra na fase final. Automatização começa hoje — continue.",
      },
      "45": {
        title: "Fase final: Automatização 🚀",
        body: "{{habit}}: Escolhas viram hábito. Faltam {{daysLeft}} dias — abra seu cartão hoje.",
      },
      "60": {
        title: "Dia 60 — Linha de chegada à vista",
        body: "{{habit}}: Faltam {{daysLeft}} dias. Esta jornada vira parte da sua identidade.",
      },
    },
    green: [
      { title: "Dia {{day}} — {{streak}} dias seguidos 🔥", body: "Você está no caminho com {{habit}}. Escolha seu pequeno passo hoje.", bodyPlanned: "Você planejou: {{plan}}. Mais um passo." },
      { title: "Sequência de {{streak}} dias continua", body: "{{habit}}: Faça o único movimento no cartão de Hoje — dia feito." },
      { title: "Dia {{day}} — Músculo fortalecendo", body: "Um micro-passo para {{habit}} hoje basta.", bodyPlanned: "Seu plano: {{plan}}. Hora de começar {{habit}}." },
      { title: "Âncora + um movimento", body: "{{habit}}: Faça sua âncora primeiro, depois escolha o passo no cartão — 30 segundos." },
      { title: "Dia {{day}} — Voto de identidade", body: '"Como alguém que faz {{habit}}, mais um voto hoje": Abra o cartão, marque.' },
      { title: "Ritmo matinal", body: "{{habit}}: Comece com a versão menor — não espere perfeição." },
      { title: "Você está em {{phase}}", body: "Nesta fase, seu cérebro fixa o padrão de {{habit}}. Repita hoje — mesmo brevemente." },
      { title: "Repetição = traço", body: "Cada repetição gasta menos energia. Deixe mais um traço para {{habit}} hoje." },
      { title: "Dia {{day}} — Faltam {{daysLeft}} dias", body: "Mais {{daysLeft}} dias para {{habit}}. Abra seu cartão, continue." },
      { title: "Momentum é real", body: "Sequência de {{streak}} dias é um traço no cérebro. Um passo pequeno e claro para {{habit}} hoje." },
      { title: "Dia {{day}} — Boa notícia", body: "Manhã de quem faz {{habit}}. Cartão aberto — seu passo está pronto." },
      { title: "Padrão se fixando", body: "Em {{phase}}, a repetição de {{habit}} parece mais familiar. Mesmo pequeno passo hoje." },
    ],
    greenHighAuto: [
      { title: "Automatização subindo", body: "Média recente de automatização: {{autoAvg}}/10. Mesmo pequeno passo para {{habit}} hoje." },
      { title: "Cérebro conhece o caminho", body: "{{habit}}: {{autoAvg}}/10 de automatização — a escolha gasta menos energia. Continue." },
      { title: "Aproximando do fluxo", body: "{{habit}} exige menos esforço agora ({{autoAvg}}/10). Abra o cartão, mantenha o ritmo." },
      { title: "Dia {{day}} — Hábito se fixando", body: "Pontuação forte {{autoAvg}}/10. Uma repetição para {{habit}} hoje basta." },
      { title: "Sinal de identidade", body: "Como quem faz {{habit}}, você pensa menos agora ({{autoAvg}}/10). Mais um voto hoje." },
      { title: "Fase final se aproximando", body: "Automatização {{autoAvg}}/10 — escolha de {{habit}} vira corporal. Pequeno passo basta." },
      { title: "Ritmo estabelecido", body: "{{habit}}: Seu cérebro reconhece esse caminho ({{autoAvg}}/10). Escolha o movimento no cartão." },
      { title: "Menos esforço, mais traço", body: "{{autoAvg}}/10 — até a versão menor de {{habit}} é um sinal forte hoje." },
    ],
    greenLowAuto: [
      { title: "Ainda exige esforço — normal", body: "Automatização {{autoAvg}}/10; {{habit}} ainda não é automático. Pequeno passo ainda deixa traço." },
      { title: "Esforço = investimento", body: "Você escolhe {{habit}} conscientemente ({{autoAvg}}/10). Abra o cartão — músculo de repetição cresce." },
      { title: "Dia {{day}} — Fase de paciência", body: "Em {{phase}}, {{autoAvg}}/10 é esperado. {{habit}}: Versão menor basta." },
      { title: "Ainda não automático", body: "{{autoAvg}}/10 — {{habit}} ainda é escolha consciente. Um movimento hoje fortalece o padrão." },
      { title: "Cérebro aprendendo", body: "Automatização {{autoAvg}}/10; cada repetição torna o caminho de {{habit}} mais familiar. Continue." },
      { title: "Pequeno passo, grande efeito", body: "{{habit}}: Com {{autoAvg}}/10, o micro-passo no cartão hoje é progresso." },
      { title: "Dias de esforço passam", body: "{{autoAvg}}/10 — sentir dificuldade é normal. A versão menor de {{habit}} ainda conta." },
      { title: "Músculo de repetição ativo", body: "{{habit}} ainda não está em fluxo ({{autoAvg}}/10). Âncora + um movimento hoje basta." },
    ],
    yellow: [
      { title: "Dia {{day}} — Ponto de deriva", body: "{{habit}}: Dias recentes foram difíceis, mas a versão menor hoje basta." },
      { title: "Deixe ontem, olhe hoje", body: "Até a versão mínima de {{habit}} conta. Abra o cartão de Hoje." },
      { title: "Dia {{day}} — Um passo basta", body: "Não espere motivação. Escolha a ação clara no cartão de {{habit}} — 10 segundos contam." },
      { title: "Não é semana de deriva", body: "{{habit}}: Ontem foi difícil, mas 2 min hoje reinicia a sequência." },
      { title: "Cérebro lembra o caminho antigo", body: "Um dia off é normal. Abra o cartão de {{habit}}, marque o menor movimento." },
      { title: "Armadilha da perfeição", body: "{{habit}}: Não precisa ser grande. 2 minutos já fazem hoje valer." },
      { title: "Rachaduras normais em {{phase}}", body: "Quedas no meio da fase muitas vezes não são falta de motivação — hábito ainda não é automático. Um passo para {{habit}} hoje." },
      { title: "Sequência reinicia", body: "{{habit}}: O cartão oferece a versão menor — comece, não termine.", bodyPlanned: "Seu plano: {{plan}}. Ainda há tempo para {{habit}}." },
      { title: "Pergunta de identidade", body: '"O que alguém que faz {{habit}} faria hoje?" — Abra o cartão, escolha um passo pequeno e real.' },
      { title: "Dia {{day}} — Escolha direção", body: "Você não precisa fazer {{habit}} completo hoje. Só escolha sua direção." },
      { title: "Sinal de inconsistência", body: "{{habit}}: Um dia perdido não quebra o padrão — recupere a direção com um pequeno passo hoje." },
      { title: "Realinhe", body: "Em {{phase}}, um movimento claro para {{habit}} hoje basta. Cartão aberto." },
    ],
    red: [
      { title: "Dia de retorno", body: "Voltar após {{misses}} dias off faz parte da jornada. O menor passo para {{habit}} hoje basta." },
      { title: "Seu cérebro ainda conhece esse caminho", body: "{{habit}}: Retornar após pausas faz parte do sistema. Abra seu cartão hoje." },
      { title: "Cair faz parte da jornada", body: "Quem faz {{habit}} se levanta. Comece com a versão menor — sem culpa." },
      { title: "Modo retorno", body: "{{habit}}: Levante-se primeiro, depois um micro-passo — check-in vem depois." },
      { title: "Jornada continua", body: "{{misses}} dias off não bloqueiam o retorno. Abra o cartão de {{habit}} — a versão menor merece." },
      { title: "Não do zero, continue", body: "{{habit}}: Pausa não zera você — o acúmulo ainda está lá. Abrir o cartão basta." },
      { title: "Recuperação também é hábito", body: "{{habit}}: As melhores jornadas não são lisas, são resilientes. Continue hoje." },
      { title: "Dê um passo hoje", body: "{{habit}}: Abra o cartão, marque um movimento — isso basta.", bodyPlanned: "Seu plano espera: {{plan}}. Mesmo pequeno, para {{habit}} hoje." },
      { title: "Você se deu permissão", body: "Alguns dias off é humano. Voltar a {{habit}} hoje é escolha suficiente." },
      { title: "Dia {{day}} — Comece de novo", body: "{{habit}}: A sequência pode ter ido, mas a jornada continua. Um passo pequeno e real hoje." },
      { title: "{{daysLeft}} dias ainda pela frente", body: "A maior parte dos 66 dias ainda vem. Volte a {{habit}} hoje." },
      { title: "Voto de identidade", body: "{{habit}}: Pausas são temporárias, hábito é duradouro. Mais um voto para sua identidade hoje." },
    ],
  },
  evening: {
    gentle: [
      { title: "Antes do dia acabar: cartão Hoje", body: "Ainda sem movimento para {{habit}}. A versão menor basta." },
      { title: "Última rodada", body: "{{habit}}: Escolha o micro-passo no cartão de Hoje — 10 segundos já servem." },
      { title: "Regra dos 2 minutos", body: "Escolha a versão menor de {{habit}} — comece, não termine." },
      { title: "Antes do dia fechar", body: "{{habit}}: Abra o cartão, marque um movimento.", bodyPlanned: "Seu plano: {{plan}}. Ainda há tempo para {{habit}}." },
      { title: "Hoje ainda conta", body: "{{habit}}: Um movimento pequeno antes do dia acabar — check-in à noite." },
      { title: "Ritmo noturno", body: "Faltam poucos minutos para {{habit}}. Abra o cartão, escolha o quanto for pequeno." },
      { title: "Não conhecimento, repetição", body: "O cérebro só aprende pela experiência. {{habit}}: Mais uma repetição esta noite." },
      { title: "Dia {{day}} — Antes da meia-noite", body: "{{habit}}: Faça a versão menor hoje. Cartão aberto para planejar amanhã também." },
      { title: "Lembrete noturno", body: "{{habit}}: Um movimento antes do dia passar — por menor que seja.", bodyPlanned: "{{plan}} ainda espera. Última rodada para {{habit}}." },
      { title: "Balanço do fim do dia", body: "{{habit}}: Ainda não hoje. Termine com um passo pequeno e real." },
      { title: "Âncora + micro-passo", body: "{{habit}}: Toque sua âncora noturna, depois escolha o menor movimento no cartão." },
      { title: "Ainda não é tarde", body: "Dia {{day}} — um passo claro para {{habit}} ainda é possível. Reduza, comece." },
    ],
    gentleFirstWeek: [
      { title: "Primeira semana — cartão Hoje", body: "Dia {{day}}: Ainda há tempo para {{habit}}. Versão menor basta — sem culpa." },
      { title: "Semana de fundação", body: "{{habit}}: Nos primeiros 7 dias, visibilidade vence perfeição. Abra o cartão." },
      { title: "Dia {{day}} — Não é última chance", body: "Um micro-passo para {{habit}} esta noite ainda constrói o padrão." },
      { title: "Novo caminho, ritmo suave", body: "Dia {{day}} — {{habit}}: Cérebro ainda aprende. Pequeno passo basta." },
      { title: "Âncora noturna", body: "{{habit}}: Na primeira semana, âncora + cartão = início forte. Ainda há tempo." },
      { title: "Antes do dia acabar", body: "{{habit}} no dia {{day}}. Se ainda sem movimento, escolha a versão menor." },
    ],
    urgent: [
      { title: "Sequência prestes a quebrar ⚠️", body: "Para manter {{streak}} dias seguidos: {{habit}} — faça o menor passo hoje." },
      { title: "Hoje ainda conta", body: "{{habit}}: Não espere motivação — abra o cartão, marque um movimento." },
      { title: "Sequência de {{streak}} dias", body: "Menor passo para {{habit}} hoje — mantenha a sequência." },
      { title: "Âncora noturna", body: "{{habit}}: Lembre sua âncora, depois escolha o movimento no cartão." },
      { title: "Antes da meia-noite", body: "{{habit}}: Sequência de {{streak}} dias. Um passo pequeno e real hoje." },
      { title: "Janela de última hora", body: "{{habit}}: Abra o cartão de hoje — 2 minutos salvam a sequência.", bodyPlanned: "Você planejou de manhã: {{plan}}. Ainda possível." },
      { title: "Pequeno mas real", body: "Você acumulou {{streak}} dias. {{habit}}: Versão menor hoje protege a sequência." },
      { title: "Intervenção noturna", body: "{{habit}}: Não um passo grande — só a repetição pequena de hoje — sequência continua." },
      { title: "Mais um voto", body: "Como quem faz {{habit}}, um último voto hoje: abra o cartão, marque." },
      { title: "Decisão antes do dia acabar", body: "{{habit}}: Sequência {{streak}} dias. 1 passo pequeno + check-in = suficiente." },
      { title: "Proteção de sequência", body: "Traço de {{streak}} dias — um movimento para {{habit}} esta noite basta." },
      { title: "Modo sequência", body: "{{habit}}: {{streak}} dias seguidos. Reduza, faça, marque." },
    ],
    recovery: [
      { title: "Oportunidade de retorno", body: "{{habit}}: Se fizer hoje, a sequência reinicia. Um movimento pequeno basta." },
      { title: "Cair faz parte do caminho", body: "Quem faz {{habit}} abre o cartão hoje. Sem culpa — só um passo." },
      { title: "Reiniciar", body: "{{habit}}: Micro-passo primeiro, check-in depois — ordem importa." },
      { title: "Esta noite conta", body: "Após dias perdidos, um movimento pequeno mantém o caminho de {{habit}} aberto." },
      { title: "Não do zero, continue", body: "{{habit}}: Voltar após alguns dias off também é escolha. Abra seu cartão hoje." },
      { title: "Cérebro conhece esse caminho", body: "{{habit}}: Retornar parece familiar ao cérebro — comece com a versão menor." },
      { title: "Momento de recuperação", body: "{{habit}}: Um movimento pequeno esta noite mostra que a jornada continua." },
      { title: "Você pausou, agora volte", body: "{{habit}}: Alguns dias off acabaram. Hoje com um passo pequeno e real.", bodyPlanned: "Seu plano: {{plan}}. {{habit}}: Volte esta noite." },
      { title: "Jornada continua", body: "Não sequência perfeita — jornada longa importa. {{habit}}: Mais um passo esta noite." },
      { title: "Antes da meia-noite", body: "{{habit}}: Ainda possível hoje. Mesmo a versão menor — esta noite conta." },
      { title: "{{misses}} dias off — ainda cedo", body: "Abra seu cartão de {{habit}} — um passo pequeno e real mantém a jornada aberta." },
      { title: "Modo retorno", body: "{{habit}}: Recuperação faz parte do sistema. Um movimento esta noite basta." },
    ],
    highEffort: [
      { title: "Dias difíceis — reduza", body: "{{habit}}: Dias recentes exigiram muito esforço. Escolha a versão mini esta noite — basta." },
      { title: "Sugestão de escala", body: "Até 2 min de {{habit}} hoje contam. Abra o cartão, reduza, continue." },
      { title: "Fase de esforço é temporária", body: "{{habit}} ainda parece difícil — normal. Menor movimento esta noite basta." },
      { title: "Alivie a carga", body: "{{habit}}: Em dias difíceis, versão mini = escolha inteligente. Abra o cartão hoje." },
      { title: "Resiliência > perfeição", body: "O menor passo para {{habit}} esta noite ainda protege a jornada." },
      { title: "Sinal de esforço", body: "Se dias recentes foram pesados para {{habit}}, hoje só âncora + 10 seg basta." },
    ],
  },
  streak: {
    milestones: {
      "7": { title: "7 dias seguidos 🔥", body: "{{habit}}: Primeira sequência semanal completa. Cérebro abre novo caminho — continue." },
      "14": { title: "14 dias de sequência! 🌱", body: "{{habit}}: 2 semanas sem pausa. Traço neural fortalecendo. Continue." },
      "21": { title: "21 dias de sequência 🏆", body: "{{habit}}: 3 semanas feitas. Esta sequência vira parte da sua identidade." },
      "30": { title: "30 dias de sequência 🎯", body: "{{habit}}: Na metade! Sequência de 30 dias mostra que o hábito é real." },
      "44": { title: "44 dias — Reforço concluído 💪", body: "{{habit}}: Entrando na fase final. Esta sequência é o início da automatização." },
      "60": { title: "60 dias de sequência 🌟", body: "{{habit}}: Faltam {{daysLeft}} dias. Esta jornada vira quem você é." },
      "66": { title: "66 dias completos! 🎉", body: "{{habit}} agora faz parte da sua identidade. Um dos hábitos que te define." },
    },
    weekly: {
      title: "{{streak}} dias de sequência 🔥",
      body: "Como quem faz {{habit}}, sua jornada de {{streak}} dias continua. Ganho de identidade é real.",
    },
    every5: {
      title: "Sequência de {{streak}} dias",
      body: "{{habit}}: {{streak}} dias de repetição deixam traço no cérebro. Continue hoje.",
    },
  },
  recovery: [
    { title: "Hora de voltar", body: "Você ficou {{misses}} dias off. {{habit}}: O resto da jornada ainda é seu. Abra seu cartão hoje." },
    { title: "Jornada continua", body: "{{misses}} dias off não bloqueiam — recuperar faz parte desta jornada. Um passo pequeno para {{habit}} hoje." },
    { title: "Não do zero, continue", body: "{{habit}}: {{misses}} dias off não apagam acúmulo. Cérebro ainda conhece esse caminho — volte hoje." },
    { title: "Voltar também é hábito", body: "{{habit}}: Retornar após cada queda fortalece o músculo. Abra seu cartão hoje." },
    { title: "Momento de recuperação", body: "Após {{misses}} dias, um passo pequeno faz diferença. {{habit}}: Dê hoje." },
    { title: "Não perder, continuar", body: "A jornada recompensa resiliência, não perfeição. {{habit}}: Volte hoje." },
    { title: "{{misses}} dias off — ainda cedo", body: "A maior parte dos 66 dias está pela frente. Abra o cartão de {{habit}} — um passo pequeno e real." },
    { title: "Voto de identidade", body: "{{habit}}: Pausas são temporárias, hábito é duradouro. Mais um voto para sua identidade hoje." },
    { title: "Cérebro esperando", body: "Após {{misses}} dias off, o caminho de {{habit}} ainda está aberto. Comece com a versão menor." },
    { title: "Dia de recuperação", body: "{{habit}}: {{misses}} dias perdidos não zeram a jornada. Volte hoje." },
  ],
};

module.exports = { tr, en, "pt-BR": ptBR };
